import type { AlgorithmEntity } from "./algorithms.ts";

export const algorithmAdditions: AlgorithmEntity[] = [
  {
    id: "learned-heuristics",
    name: "Learned Heuristics",
    aliases: ["Neural heuristics", "Learned search heuristic"],
    fields: ["Foundations", "AI / ML"],
    families: ["Heuristic search", "Learning-to-search", "Planning"],
    chapterSlugs: ["02-search-graphs-ordering-indexing", "09-combination-research-map", "13-ai-reasoning-alignment-agents"],
    summary: "Use a learned model to estimate cost-to-go, ranking, pruning value, or search priority inside an explicit search procedure.",
    motivation: "Hand-designed heuristics can be weak or expensive in high-dimensional domains even when historical solved instances contain useful guidance.",
    contribution: "Learned heuristics inject data-derived structure into classical search while leaving the outer search algorithm responsible for explicit state exploration and, when designed carefully, correctness safeguards.",
    assumptions: ["Training or solved-instance data is informative about future search states", "Search can tolerate imperfect heuristic estimates or can bound their influence"],
    complexity: { note: "Adds model-inference cost per scored state while potentially reducing the number of expanded states by orders of magnitude." },
    maturity: "Active research",
    implementation: ["Define the search signal to predict: value, cost-to-go, node priority, branching choice, or prune probability", "Train on solved trajectories or self-generated search data", "Calibrate or bound heuristic influence when guarantees matter", "Measure total wall-clock cost rather than node-count reduction alone"],
    failureModes: ["Distribution shift to unseen state regions", "Heuristic overconfidence can prune useful branches", "Inference cost can erase search savings", "Training labels inherit biases from the solver that generated them"],
    relations: [
      { target: "a-star", type: "combines-with", note: "Learned cost-to-go estimates can provide A* heuristics, optionally constrained to retain admissibility or bounded suboptimality." },
      { target: "branch-and-bound", type: "combines-with", note: "Learned branching, bounding, or node-selection policies can reduce combinatorial search effort." },
      { target: "transformer-attention", type: "combines-with", note: "Transformers are one possible learned model family for heuristic prediction; they are not required by the concept." },
    ],
    tags: ["search", "heuristic", "learning-to-search"],
    openQuestions: ["How can learned heuristics expose uncertainty so the solver knows when to distrust them?", "Which guarantee-preserving wrappers give the best speed/optimality tradeoff?"],
  },
  {
    id: "branch-and-bound",
    name: "Branch and Bound",
    aliases: ["B&B", "Branch-and-bound"],
    fields: ["Foundations"],
    families: ["Combinatorial optimization", "Search", "Exact optimization"],
    chapterSlugs: ["03-optimization-randomization-constraints", "09-combination-research-map"],
    summary: "Systematically partition an optimization problem into subproblems and prune any branch whose bound cannot beat the incumbent solution.",
    motivation: "Exhaustive combinatorial search is often impossible, but many subspaces can be ruled out without enumerating every candidate.",
    contribution: "Branch and bound combines decomposition, incumbent solutions, and mathematically valid upper/lower bounds to retain exactness while pruning large parts of the search tree.",
    assumptions: ["Subproblems admit valid bounds", "The search domain can be recursively partitioned", "An incumbent objective value can be maintained"],
    complexity: { time: "Exponential in the worst case", space: "Depends on traversal strategy and stored frontier" },
    maturity: "Production-proven",
    implementation: ["Define branching variables/decisions", "Compute valid relaxation-based or analytical bounds", "Maintain best feasible incumbent", "Prune branches whose best possible objective cannot improve the incumbent", "Choose node ordering to discover strong incumbents early"],
    failureModes: ["Weak bounds yield near-exhaustive search", "Poor branching creates enormous trees", "Numerical tolerances can invalidate pruning logic", "Learned pruning without safeguards can lose exactness"],
    relations: [
      { target: "learned-heuristics", type: "combines-with", note: "Learning can rank branches, propose incumbents, or estimate strong branching while exact bounds remain the correctness boundary." },
      { target: "dynamic-programming", type: "alternative-to", note: "Both exploit problem structure, but branch-and-bound searches bounded subspaces while DP memoizes repeated states." },
    ],
    tags: ["optimization", "exact-search", "bounds"],
    openQuestions: ["Which learned policies improve branching without making worst-case behavior or reproducibility unacceptable?"],
  },
  {
    id: "neural-ucb",
    name: "NeuralUCB",
    aliases: ["Neural Upper Confidence Bound"],
    fields: ["AI / ML"],
    families: ["Contextual bandits", "Neural uncertainty", "Online learning"],
    chapterSlugs: ["08-bandits-contextual-bandits-linucb", "14-uncertainty-causal-active-continual-meta-learning"],
    summary: "Extend UCB-style contextual decision making beyond fixed linear features by using neural representations together with an uncertainty/confidence approximation.",
    motivation: "LinUCB is efficient and interpretable but can underfit strongly nonlinear reward structure.",
    contribution: "NeuralUCB keeps optimism-driven exploration while replacing a fixed linear reward representation with a learned nonlinear function or neural tangent-style uncertainty model.",
    assumptions: ["The neural model can learn useful reward structure online", "The confidence approximation remains informative enough to drive exploration"],
    complexity: { note: "Substantially more expensive than LinUCB because neural updates and uncertainty statistics are required; exact cost depends on approximation." },
    maturity: "Active research",
    implementation: ["Train/update neural reward predictor online or in batches", "Maintain a confidence approximation from gradients/features", "Score actions using prediction plus uncertainty bonus", "Control replay, drift, and retraining cadence"],
    failureModes: ["Miscalibrated uncertainty", "Representation drift invalidates confidence estimates", "High latency", "Feedback loops and unstable online training"],
    relations: [
      { target: "linucb", type: "derived-from", note: "NeuralUCB generalizes the confidence-bound contextual-bandit idea to nonlinear learned representations." },
      { target: "conformal-prediction", type: "combines-with", note: "Conformal calibration may help characterize predictive uncertainty, though standard coverage is not itself a bandit exploration guarantee." },
    ],
    tags: ["bandit", "neural", "uncertainty"],
    openQuestions: ["Can nonlinear contextual bandits obtain uncertainty that is both computationally cheap and reliable under representation drift?"],
  },
  {
    id: "embedding-models",
    name: "Embedding Models",
    aliases: ["Vector embeddings", "Representation embeddings"],
    fields: ["AI / ML", "Foundations"],
    families: ["Representation learning", "Retrieval", "Metric learning"],
    chapterSlugs: ["06-representation-similarity-compression-parsing", "11-neural-architectures-attention-ssm-moe-gnn"],
    summary: "Map discrete or high-dimensional objects into continuous vectors whose geometry encodes task-relevant similarity, semantics, or structure.",
    motivation: "Raw symbols, documents, images, users, and graph nodes are difficult to compare directly with generic algorithms.",
    contribution: "Embeddings transform heterogeneous objects into a common numeric space where similarity search, clustering, ranking, and downstream learning become simple geometric operations.",
    assumptions: ["A training objective or representation process can align vector geometry with useful semantics", "Chosen similarity metric matches the embedding objective"],
    complexity: { note: "Inference cost depends on the encoder; storage and retrieval cost scale with embedding dimension and corpus size." },
    maturity: "Production-proven",
    implementation: ["Choose encoder/objective aligned with downstream similarity", "Normalize when metric assumptions require it", "Version embeddings together with the model", "Monitor representation drift before mixing vectors from different model versions"],
    failureModes: ["Semantic collapse or anisotropy", "Domain shift", "Similarity does not imply utility", "Embedding-version mismatch", "Sensitive attributes can be encoded unintentionally"],
    relations: [
      { target: "hnsw", type: "used-by", note: "HNSW indexes embedding vectors for approximate nearest-neighbor search." },
      { target: "transformer-attention", type: "used-by", note: "Transformer encoders are a major source of modern text and multimodal embeddings." },
      { target: "linucb", type: "combines-with", note: "Embeddings can provide compact contextual/action features for contextual bandit reranking." },
    ],
    tags: ["embedding", "representation", "vector"],
    openQuestions: ["How should embedding uncertainty and version drift propagate into downstream retrieval and decision systems?"],
  },
  {
    id: "sat-smt-solving",
    name: "SAT / SMT Solving",
    aliases: ["SAT solver", "SMT solver", "Satisfiability modulo theories"],
    fields: ["Foundations", "Cybersecurity"],
    families: ["Constraint solving", "Formal methods", "Automated reasoning"],
    chapterSlugs: ["03-optimization-randomization-constraints", "34-security-analysis-symbolic-execution-fuzzing"],
    summary: "Decide whether logical constraints are satisfiable, with SMT extending Boolean SAT to theories such as arithmetic, arrays, bit-vectors, and uninterpreted functions.",
    motivation: "Many verification, planning, synthesis, and security problems can be expressed more naturally as constraints than as explicit procedural search.",
    contribution: "Modern SAT/SMT solvers combine conflict-driven search, learned clauses, theory reasoning, propagation, and backtracking into powerful general-purpose reasoning engines.",
    assumptions: ["The problem can be encoded faithfully in supported logic/theories", "Solver resource usage is acceptable for the constraint structure"],
    complexity: { time: "NP-complete for propositional SAT in the worst case; richer theories vary", space: "Instance- and solver-dependent" },
    maturity: "Production-proven",
    implementation: ["Choose the narrowest suitable theory", "Encode invariants and bounds precisely", "Use incremental solving when constraints evolve", "Inspect unsat cores/models where useful", "Avoid accidental nonlinear or quantified blowups"],
    failureModes: ["Encoding bugs", "Pathological formulas", "Theory combination blowups", "Timeouts", "Bit-width or overflow semantics mismatches"],
    relations: [
      { target: "symbolic-execution", type: "used-by", note: "Symbolic execution relies on SAT/SMT solvers to decide path feasibility and produce concrete satisfying inputs." },
      { target: "zero-knowledge-proofs", type: "combines-with", note: "Solver/formal techniques can help validate constraint systems and compiler transformations used by proof pipelines." },
      { target: "branch-and-bound", type: "alternative-to", note: "Some discrete optimization problems can be handled through SAT/SMT encodings instead of explicit branch-and-bound." },
    ],
    tags: ["sat", "smt", "formal"],
    openQuestions: ["How can learned branching/proposal mechanisms accelerate solvers while keeping proof-producing verification trustworthy?"],
  },
  {
    id: "error-correcting-codes",
    name: "Error-Correcting Codes",
    aliases: ["ECC", "Classical error correction"],
    fields: ["Foundations", "Quantum"],
    families: ["Coding theory", "Information theory", "Decoding"],
    chapterSlugs: ["06-representation-similarity-compression-parsing", "24-quantum-error-correction-decoding"],
    summary: "Add structured redundancy so a receiver can detect and correct corruption introduced by noisy channels or storage.",
    motivation: "Reliable communication and computation require recovery from errors without retransmitting or duplicating all information naively.",
    contribution: "Coding theory links algebraic/combinatorial structure, redundancy, distance, and efficient decoding to achievable reliability under noise.",
    assumptions: ["Noise model is compatible enough with the chosen code/decoder", "Redundancy overhead is acceptable"],
    complexity: { note: "Encoding/decoding cost depends on the code family; practical LDPC/polar/turbo decoders use iterative or structured algorithms." },
    maturity: "Production-proven",
    implementation: ["Choose code rate and distance for the channel", "Encode using generator/structured transform", "Compute syndrome or soft information", "Decode with algebraic, belief-propagation, list, or other code-specific method"],
    failureModes: ["Burst/correlated noise outside decoder assumptions", "Error floor", "Latency under iterative decoding", "Rate/reliability tradeoffs"],
    relations: [
      { target: "surface-code-decoding", type: "used-by", note: "Quantum error correction extends coding ideas to protect logical quantum information, with surface-code decoding operating on syndrome information." },
      { target: "bayesian-inference", type: "combines-with", note: "Probabilistic decoding can be formulated as posterior inference over codewords or error patterns." },
    ],
    tags: ["coding", "decoding", "reliability"],
    openQuestions: ["Which classical decoder ideas transfer most effectively to low-latency quantum decoding under correlated noise?"],
  },
  {
    id: "lattice-problems",
    name: "Lattice Problems and Reduction",
    aliases: ["Lattice cryptography foundation", "LWE/SIS foundation", "LLL/BKZ"],
    fields: ["Cybersecurity", "Foundations"],
    families: ["Lattices", "Computational hardness", "Cryptography"],
    chapterSlugs: ["31-post-quantum-cryptography", "35-cryptanalysis-side-channels-adversarial-methods"],
    summary: "Study geometric and algebraic problems over discrete lattices, including shortest/closest vectors and noisy linear equations that underpin major post-quantum constructions.",
    motivation: "Post-quantum cryptography needs hardness assumptions believed resistant to known efficient quantum algorithms while remaining implementable on classical hardware.",
    contribution: "Lattice problems provide worst-case/average-case hardness connections, efficient polynomial arithmetic variants, and a rich foundation for KEMs, signatures, and homomorphic encryption.",
    assumptions: ["Relevant lattice/LWE/SIS assumptions remain computationally hard at chosen parameters", "Implementations do not leak secrets through side channels"],
    complexity: { note: "Security estimates depend on dimension, modulus, error distribution, and the cost of lattice-reduction attacks such as BKZ." },
    maturity: "Production-proven",
    implementation: ["Use standardized constructions rather than inventing schemes", "Select vetted parameter sets", "Use constant-time arithmetic", "Model concrete reduction/attack costs for research comparisons"],
    failureModes: ["Bad parameters", "Side-channel leakage", "Implementation errors in polynomial arithmetic/sampling", "Overstated security from inaccurate attack-cost models"],
    relations: [
      { target: "ml-kem", type: "used-by", note: "ML-KEM is built from module-lattice assumptions closely related to LWE-style hardness." },
      { target: "fhe", type: "used-by", note: "Major FHE families rely on LWE/RLWE-style lattice assumptions." },
    ],
    tags: ["lattice", "lwe", "pqc"],
    openQuestions: ["How should concrete lattice-security estimators evolve as cryptanalysis and hardware assumptions change?"],
  },
  {
    id: "secure-multiparty-computation",
    name: "Secure Multi-Party Computation",
    aliases: ["MPC", "SMPC", "Secure computation"],
    fields: ["Cybersecurity", "AI / ML"],
    families: ["Privacy-preserving computation", "Distributed cryptography"],
    chapterSlugs: ["33-mpc-homomorphic-encryption-differential-privacy"],
    summary: "Allow mutually distrustful parties to compute a joint function while limiting what each party learns beyond the intended output.",
    motivation: "Organizations often need to collaborate over sensitive data that cannot be pooled in plaintext.",
    contribution: "MPC uses secret sharing, garbled circuits, oblivious transfer, preprocessing, and protocol-specific techniques to separate joint computation from raw-data disclosure.",
    assumptions: ["Threat model is specified: semi-honest or malicious, corruption threshold, network model", "Cryptographic primitives and randomness are sound"],
    complexity: { note: "Communication rounds/bandwidth often dominate; arithmetic and Boolean protocols have different cost profiles." },
    maturity: "Production-proven",
    implementation: ["Choose threat model first", "Select arithmetic/Boolean sharing protocol", "Use preprocessing such as Beaver triples when appropriate", "Batch operations to reduce communication", "Authenticate shares under malicious security"],
    failureModes: ["Unexpected communication cost", "Incorrect threat model", "Participant dropout", "Side channels around the protocol", "Leakage through outputs themselves"],
    relations: [
      { target: "fhe", type: "alternative-to", note: "Both support private computation; MPC distributes trust across parties while FHE can enable noninteractive encrypted evaluation." },
      { target: "zero-knowledge-proofs", type: "combines-with", note: "ZK proofs can attest that parties or services followed an agreed private-computation protocol." },
    ],
    tags: ["mpc", "privacy", "distributed"],
    openQuestions: ["Which hybrid FHE/MPC/ZK splits minimize communication and proving cost for large AI workloads?"],
  },
];
