import type { ResearchField } from "@/lib/taxonomy";

export type MaturityLevel =
  | "Established foundation"
  | "Production-proven"
  | "Active research"
  | "Emerging";

export type RelationType =
  | "derived-from"
  | "generalizes"
  | "special-case-of"
  | "alternative-to"
  | "combines-with"
  | "depends-on"
  | "used-by"
  | "approximates"
  | "secures"
  | "accelerates";

export type AlgorithmRelation = {
  target: string;
  type: RelationType;
  note: string;
};

export type ComplexityRecord = {
  time?: string;
  space?: string;
  sample?: string;
  note?: string;
};

export type AlgorithmEntity = {
  id: string;
  name: string;
  aliases: string[];
  fields: ResearchField[];
  families: string[];
  chapterSlugs: string[];
  summary: string;
  motivation: string;
  contribution: string;
  assumptions: string[];
  complexity?: ComplexityRecord;
  maturity: MaturityLevel;
  implementation: string[];
  failureModes: string[];
  relations: AlgorithmRelation[];
  tags: string[];
  openQuestions: string[];
};

export const algorithms: AlgorithmEntity[] = [
  {
    id: "dynamic-programming",
    name: "Dynamic Programming",
    aliases: ["DP"],
    fields: ["Foundations"],
    families: ["Optimization", "Recurrence", "Sequential decision"],
    chapterSlugs: ["01-core-problem-solving-paradigms", "05-probabilistic-control-reinforcement-learning"],
    summary: "Solve overlapping subproblems once and compose their stored solutions through an optimal-substructure recurrence.",
    motivation: "Naive recursion repeatedly solves the same subproblems and can turn tractable structure into exponential work.",
    contribution: "Dynamic programming makes state and recurrence explicit, trading memory for reusable computation and globally consistent optimization.",
    assumptions: ["Subproblems can be represented by a finite or manageable state", "Useful recurrence or Bellman-style decomposition exists"],
    complexity: { note: "Usually proportional to number of states × work per transition; exact bounds depend on the state representation." },
    maturity: "Established foundation",
    implementation: ["Define minimal sufficient state", "Write recurrence before choosing top-down or bottom-up evaluation", "Store only the frontier when full history is unnecessary"],
    failureModes: ["State explosion", "Incorrect state omits information needed for optimal decisions", "Overlapping subproblems are too weak to justify memoization"],
    relations: [
      { target: "q-learning", type: "used-by", note: "Bellman decompositions connect dynamic programming to reinforcement learning." },
      { target: "a-star", type: "combines-with", note: "DP-derived cost-to-go functions can act as exact or approximate search heuristics." },
    ],
    tags: ["memoization", "bellman", "optimal-substructure"],
    openQuestions: ["How can learned representations compress high-dimensional DP state without destroying guarantees?"],
  },
  {
    id: "a-star",
    name: "A* Search",
    aliases: ["A-star", "A*"],
    fields: ["Foundations", "AI / ML"],
    families: ["Graph search", "Heuristic search", "Planning"],
    chapterSlugs: ["02-search-graphs-ordering-indexing", "09-combination-research-map"],
    summary: "Best-first graph search using path cost plus a heuristic estimate of remaining cost.",
    motivation: "Uniform-cost search wastes effort expanding states that are clearly far from a goal when useful domain knowledge exists.",
    contribution: "A* integrates exact accumulated cost with a heuristic while retaining optimality under admissibility/consistency conditions.",
    assumptions: ["A graph/state-space formulation exists", "Edge costs are meaningful", "A heuristic can estimate remaining cost"],
    complexity: { time: "Worst-case exponential in solution depth", space: "Can be exponential because the frontier is retained" },
    maturity: "Established foundation",
    implementation: ["Use a priority queue keyed by f=g+h", "Track best-known g score per state", "Reopen states when using inconsistent heuristics if correctness requires it"],
    failureModes: ["Weak heuristic degenerates toward Dijkstra/uniform-cost search", "Memory exhaustion", "Inadmissible heuristic may lose optimality"],
    relations: [
      { target: "dijkstra", type: "generalizes", note: "With h=0, A* reduces to Dijkstra/uniform-cost search." },
      { target: "dynamic-programming", type: "combines-with", note: "Exact or learned cost-to-go estimates can guide A*." },
      { target: "transformer-attention", type: "combines-with", note: "Learned models can propose or score heuristics while search preserves explicit state exploration." },
    ],
    tags: ["search", "planning", "heuristic"],
    openQuestions: ["How can uncertainty-aware learned heuristics improve search while preserving useful bounds?"],
  },
  {
    id: "dijkstra",
    name: "Dijkstra's Algorithm",
    aliases: ["Dijkstra"],
    fields: ["Foundations"],
    families: ["Graph search", "Shortest path"],
    chapterSlugs: ["02-search-graphs-ordering-indexing"],
    summary: "Computes shortest paths from a source in graphs with non-negative edge weights.",
    motivation: "Breadth-first search is insufficient when edges carry unequal costs.",
    contribution: "Greedily finalizes the smallest tentative distance, exploiting non-negative costs to make that choice safe.",
    assumptions: ["No negative edge weights"],
    complexity: { time: "O((V+E) log V) with a binary heap", space: "O(V+E) including graph storage" },
    maturity: "Production-proven",
    implementation: ["Use an adjacency list", "Use a min-priority queue", "Ignore stale queue entries or support decrease-key"],
    failureModes: ["Negative weights invalidate correctness", "Dense graphs may favor alternative priority-queue/data representations"],
    relations: [{ target: "a-star", type: "special-case-of", note: "A* with a zero heuristic behaves like Dijkstra." }],
    tags: ["graph", "shortest-path", "priority-queue"],
    openQuestions: ["Which learned indexing or graph-partitioning methods most effectively reduce practical shortest-path latency?"],
  },
  {
    id: "bayesian-inference",
    name: "Bayesian Inference",
    aliases: ["Bayes", "Bayesian updating"],
    fields: ["Foundations", "AI / ML"],
    families: ["Probability", "Uncertainty", "Inference"],
    chapterSlugs: ["05-probabilistic-control-reinforcement-learning", "14-uncertainty-causal-active-continual-meta-learning"],
    summary: "Update beliefs over hypotheses or parameters by combining prior probability with observed evidence.",
    motivation: "Point estimates hide uncertainty and make sequential decisions brittle when evidence is incomplete.",
    contribution: "Bayesian inference turns uncertainty into an explicit posterior distribution that can be queried or propagated into decisions.",
    assumptions: ["A probabilistic model and prior are specified", "Likelihood evaluation or approximation is possible"],
    complexity: { note: "Exact inference is often intractable; practical cost depends on conjugacy, factorization, variational approximations, or sampling." },
    maturity: "Established foundation",
    implementation: ["Model prior and likelihood separately", "Use conjugacy where available", "Use MCMC or variational inference for difficult posteriors"],
    failureModes: ["Model misspecification", "Poor priors in data-scarce regimes", "Approximate inference can be overconfident"],
    relations: [
      { target: "thompson-sampling", type: "used-by", note: "Thompson sampling acts by sampling from posterior beliefs over rewards." },
      { target: "bayesian-optimization", type: "used-by", note: "Bayesian optimization maintains uncertainty over expensive objectives." },
    ],
    tags: ["probability", "posterior", "uncertainty"],
    openQuestions: ["How should calibrated uncertainty be maintained under distribution shift in adaptive systems?"],
  },
  {
    id: "ucb1",
    name: "UCB1",
    aliases: ["Upper Confidence Bound", "UCB"],
    fields: ["Foundations", "AI / ML"],
    families: ["Bandits", "Online learning", "Exploration"],
    chapterSlugs: ["08-bandits-contextual-bandits-linucb"],
    summary: "A multi-armed bandit rule that chooses actions by optimistic reward estimates plus shrinking confidence bonuses.",
    motivation: "Greedy action selection can lock onto an inferior arm because early observations are noisy.",
    contribution: "UCB makes exploration systematic by preferring actions that are either promising or still uncertain.",
    assumptions: ["Rewards are bounded or otherwise admit concentration bounds", "Basic UCB assumes stationary arm reward distributions"],
    complexity: { time: "O(K) scoring per decision in the simplest implementation", space: "O(K)" },
    maturity: "Established foundation",
    implementation: ["Track count and empirical mean per arm", "Initialize untried arms explicitly", "Use a confidence bonus tied to log time / pull count"],
    failureModes: ["Nonstationary rewards", "Poorly scaled rewards", "No context means heterogeneous situations are conflated"],
    relations: [
      { target: "linucb", type: "generalizes", note: "LinUCB extends confidence-bound action selection with contextual linear reward models." },
      { target: "thompson-sampling", type: "alternative-to", note: "Both address exploration/exploitation using uncertainty, but via optimism versus posterior sampling." },
    ],
    tags: ["bandit", "online-learning", "exploration"],
    openQuestions: ["How should confidence bonuses adapt under delayed and censored feedback?"],
  },
  {
    id: "linucb",
    name: "LinUCB",
    aliases: ["Linear Upper Confidence Bound"],
    fields: ["Foundations", "AI / ML"],
    families: ["Contextual bandits", "Online learning", "Linear models"],
    chapterSlugs: ["08-bandits-contextual-bandits-linucb", "09-combination-research-map"],
    summary: "A contextual bandit algorithm that scores each action using predicted linear reward plus a confidence bonus.",
    motivation: "Ordinary bandits ignore context; supervised predictors exploit context but do not automatically explore uncertain actions.",
    contribution: "LinUCB combines linear reward estimation and uncertainty-aware optimism into a simple online decision rule.",
    assumptions: ["Expected reward is reasonably linear in chosen features", "Feedback for the chosen action is observable", "Context and reward scale are controlled"],
    complexity: { time: "Typically O(K d²) per decision with direct quadratic forms; lower with shared structure/optimized linear algebra", space: "O(K d²) for disjoint models" },
    maturity: "Production-proven",
    implementation: ["Maintain A and b sufficient statistics", "Solve Aθ=b instead of explicitly inverting when possible", "Use Sherman–Morrison/cholesky updates carefully", "Log propensities and chosen context for evaluation"],
    failureModes: ["Nonlinear reward structure", "Feature drift", "Delayed feedback", "Unobserved confounding in offline evaluation"],
    relations: [
      { target: "ucb1", type: "derived-from", note: "It carries UCB optimism into a contextual linear model." },
      { target: "thompson-sampling", type: "alternative-to", note: "Linear Thompson Sampling is a posterior-sampling alternative." },
      { target: "coverage-guided-fuzzing", type: "combines-with", note: "Mutation families can be actions and coverage gain can be reward." },
    ],
    tags: ["contextual-bandit", "confidence-bound", "online-decision"],
    openQuestions: ["How can nonlinear representation learning be added without losing useful uncertainty semantics?", "How should LinUCB adapt under rapid nonstationarity?"],
  },
  {
    id: "thompson-sampling",
    name: "Thompson Sampling",
    aliases: ["Posterior sampling"],
    fields: ["Foundations", "AI / ML"],
    families: ["Bandits", "Bayesian decision-making", "Exploration"],
    chapterSlugs: ["08-bandits-contextual-bandits-linucb", "14-uncertainty-causal-active-continual-meta-learning"],
    summary: "Choose an action by sampling a plausible reward model from the posterior and acting greedily under that sample.",
    motivation: "Exploration should reflect uncertainty rather than a fixed random rate.",
    contribution: "Posterior sampling turns epistemic uncertainty directly into randomized action selection with strong empirical and theoretical behavior.",
    assumptions: ["A posterior or useful posterior approximation can be maintained"],
    complexity: { note: "Depends on posterior family; conjugate bandits can be O(K), contextual/general models can be substantially more expensive." },
    maturity: "Production-proven",
    implementation: ["Maintain posterior sufficient statistics", "Sample once per decision", "Choose the action optimal under the sampled parameters"],
    failureModes: ["Misspecified posterior", "Approximate posterior collapse", "Nonstationarity without forgetting"],
    relations: [
      { target: "bayesian-inference", type: "depends-on", note: "Its exploration behavior is generated from posterior uncertainty." },
      { target: "ucb1", type: "alternative-to", note: "Posterior sampling is an alternative to confidence-bound optimism." },
      { target: "linucb", type: "alternative-to", note: "Linear Thompson Sampling targets a similar contextual setting." },
    ],
    tags: ["bandit", "bayesian", "exploration"],
    openQuestions: ["Which posterior approximations remain reliable for large neural contextual bandits?"],
  },
  {
    id: "bayesian-optimization",
    name: "Bayesian Optimization",
    aliases: ["BO"],
    fields: ["Foundations", "AI / ML", "Quantum"],
    families: ["Black-box optimization", "Sequential design", "Uncertainty"],
    chapterSlugs: ["03-optimization-randomization-constraints", "14-uncertainty-causal-active-continual-meta-learning", "40-ai-quantum-cybersecurity-combination-map"],
    summary: "Optimize expensive black-box objectives by fitting an uncertainty-aware surrogate and selecting informative evaluations with an acquisition function.",
    motivation: "Gradient-free brute-force tuning is wasteful when each experiment is expensive.",
    contribution: "BO spends evaluations where predicted quality and information value justify the cost.",
    assumptions: ["Objective evaluations are expensive relative to surrogate optimization", "A surrogate can express useful smoothness/structure"],
    complexity: { note: "Gaussian-process variants often incur cubic scaling in observation count without approximations." },
    maturity: "Production-proven",
    implementation: ["Normalize inputs and objective", "Fit/update surrogate", "Optimize acquisition function", "Record noise and failed experiments explicitly"],
    failureModes: ["High-dimensional search", "Poor kernel/prior", "Nonstationary objectives", "Acquisition optimization failures"],
    relations: [
      { target: "bayesian-inference", type: "depends-on", note: "Uncertainty over the objective is central to acquisition decisions." },
      { target: "qaoa", type: "combines-with", note: "Classical BO can tune variational quantum parameters under expensive noisy evaluations." },
    ],
    tags: ["optimization", "surrogate", "experiment-design"],
    openQuestions: ["How should BO exploit structured simulator priors while remaining robust to model mismatch?"],
  },
  {
    id: "hnsw",
    name: "HNSW",
    aliases: ["Hierarchical Navigable Small World"],
    fields: ["Foundations", "AI / ML"],
    families: ["Approximate nearest neighbor", "Graph indexing", "Retrieval"],
    chapterSlugs: ["06-representation-similarity-compression-parsing", "09-combination-research-map"],
    summary: "A layered proximity graph for efficient approximate nearest-neighbor retrieval in high-dimensional vector spaces.",
    motivation: "Exact nearest-neighbor search becomes expensive at modern embedding scale and dimensionality.",
    contribution: "HNSW combines navigable small-world graphs with hierarchy to achieve high-recall low-latency retrieval in practice.",
    assumptions: ["A meaningful distance/similarity metric exists", "Approximate retrieval is acceptable"],
    complexity: { note: "Empirical logarithmic-like query behavior is common, but practical performance depends heavily on graph parameters and data geometry." },
    maturity: "Production-proven",
    implementation: ["Tune M, efConstruction, and efSearch", "Normalize vectors when using cosine similarity as dot product", "Measure recall-latency-memory tradeoffs"],
    failureModes: ["Memory overhead", "Poor recall under bad parameters", "Dynamic deletion/update complexity"],
    relations: [
      { target: "transformer-attention", type: "combines-with", note: "Embedding models commonly feed HNSW retrieval systems." },
      { target: "linucb", type: "combines-with", note: "HNSW can retrieve candidates that a contextual bandit subsequently reranks." },
    ],
    tags: ["vector-search", "retrieval", "graph"],
    openQuestions: ["How can online feedback alter graph traversal or candidate budgets without degrading recall guarantees?"],
  },
  {
    id: "adamw",
    name: "AdamW",
    aliases: ["Adam with decoupled weight decay"],
    fields: ["AI / ML"],
    families: ["Optimization", "Gradient methods", "Deep learning"],
    chapterSlugs: ["10-ai-optimization-learning-theory"],
    summary: "Adaptive first-order optimization with momentum-like moments and weight decay decoupled from the gradient update.",
    motivation: "Adaptive optimizers train deep models efficiently, but L2 regularization and adaptive scaling interact in unintuitive ways in Adam.",
    contribution: "AdamW separates weight decay from the gradient transformation, making regularization behavior easier to reason about and tune.",
    assumptions: ["Differentiable objective", "Stochastic gradients are available"],
    complexity: { time: "O(P) per parameter update", space: "O(P) extra moment state" },
    maturity: "Production-proven",
    implementation: ["Maintain first and second moments", "Apply bias correction", "Apply decoupled parameter shrinkage", "Use scheduler/warmup appropriate to model scale"],
    failureModes: ["Learning-rate sensitivity", "Can generalize differently from SGD", "Large optimizer state for huge models"],
    relations: [{ target: "transformer-attention", type: "used-by", note: "AdamW is a common optimizer for Transformer training." }],
    tags: ["optimizer", "deep-learning", "gradient"],
    openQuestions: ["Which optimizer states can be compressed or approximated without destabilizing large-model training?"],
  },
  {
    id: "transformer-attention",
    name: "Transformer Attention",
    aliases: ["Scaled dot-product attention", "Self-attention", "Multi-head attention"],
    fields: ["AI / ML"],
    families: ["Neural architecture", "Sequence modeling", "Representation learning"],
    chapterSlugs: ["11-neural-architectures-attention-ssm-moe-gnn", "13-ai-reasoning-alignment-agents"],
    summary: "Content-addressable neural interaction where queries weight key/value representations, enabling flexible token-to-token information flow.",
    motivation: "Fixed recurrent state bottlenecks make long-range dependency modeling and parallel training difficult.",
    contribution: "Attention allows each position to dynamically retrieve information from other positions while remaining highly parallelizable during training.",
    assumptions: ["Inputs can be embedded into compatible query/key/value spaces"],
    complexity: { time: "O(n²d) for dense attention", space: "O(n²) attention matrix without memory-efficient kernels" },
    maturity: "Production-proven",
    implementation: ["Scale dot products by key dimension", "Mask causally when autoregressive", "Use stable softmax", "Use FlashAttention-style kernels for IO efficiency when available"],
    failureModes: ["Quadratic context cost", "Attention weights are not explanations", "Long-context retrieval can still fail"],
    relations: [
      { target: "state-space-models", type: "alternative-to", note: "SSMs offer a different long-sequence computation pattern." },
      { target: "mixture-of-experts", type: "combines-with", note: "MoE feed-forward blocks can add conditional compute to Transformer stacks." },
      { target: "hnsw", type: "combines-with", note: "Transformer embeddings often feed retrieval indices." },
    ],
    tags: ["transformer", "attention", "sequence"],
    openQuestions: ["Which sparse or recurrent mechanisms preserve quality while reducing long-context compute and memory?"],
  },
  {
    id: "state-space-models",
    name: "Selective State-Space Models",
    aliases: ["SSM", "Selective SSM", "Mamba-style models"],
    fields: ["AI / ML"],
    families: ["Neural architecture", "Sequence modeling", "State-space"],
    chapterSlugs: ["11-neural-architectures-attention-ssm-moe-gnn"],
    summary: "Sequence models that propagate compact recurrent state using structured dynamical-system updates, with selective variants adapting state transitions to content.",
    motivation: "Dense attention scales quadratically with sequence length and stores large key/value histories at inference time.",
    contribution: "Modern SSMs provide linear-time sequence processing with hardware-aware scans and content-dependent state updates.",
    assumptions: ["Relevant sequence information can be compressed into recurrent state"],
    complexity: { time: "O(n) sequence length up to model-width factors", space: "Typically linear or constant-in-context recurrent inference state depending on formulation" },
    maturity: "Active research",
    implementation: ["Use stable parameterizations of continuous/discrete state dynamics", "Use parallel scan kernels during training", "Benchmark recurrent inference separately from training throughput"],
    failureModes: ["State bottleneck can lose exact retrieval", "Kernel quality is hardware-sensitive", "Architectural behavior is less mature than standard attention"],
    relations: [
      { target: "transformer-attention", type: "alternative-to", note: "Both model sequences but use different memory/computation structures." },
      { target: "surface-code-decoding", type: "combines-with", note: "Sequential syndrome streams are a candidate domain for recurrent state models." },
    ],
    tags: ["ssm", "sequence", "linear-time"],
    openQuestions: ["Which tasks require explicit content-addressable memory rather than compressed recurrent state?"],
  },
  {
    id: "mixture-of-experts",
    name: "Mixture of Experts",
    aliases: ["MoE", "Sparse MoE"],
    fields: ["AI / ML"],
    families: ["Neural architecture", "Conditional computation", "Routing"],
    chapterSlugs: ["11-neural-architectures-attention-ssm-moe-gnn"],
    summary: "Conditionally route each input/token through a small subset of expert subnetworks to increase parameter capacity without proportional compute.",
    motivation: "Scaling every parameter for every token makes dense models computationally expensive.",
    contribution: "Sparse expert routing separates model capacity from per-example active computation.",
    assumptions: ["A router can learn useful specialization", "Distributed systems can move tokens to experts efficiently"],
    complexity: { note: "Active FLOPs depend on selected experts, but communication and load-balancing overhead can dominate at scale." },
    maturity: "Production-proven",
    implementation: ["Top-k router", "Capacity limits", "Load-balancing auxiliary objectives", "Expert parallel communication"],
    failureModes: ["Expert collapse", "Hot experts", "Communication bottlenecks", "Routing instability"],
    relations: [{ target: "transformer-attention", type: "combines-with", note: "Sparse experts commonly replace dense feed-forward sublayers in Transformers." }],
    tags: ["moe", "routing", "conditional-compute"],
    openQuestions: ["Can routing become more uncertainty-aware and dynamically budget compute per token?"],
  },
  {
    id: "graph-neural-networks",
    name: "Graph Neural Networks",
    aliases: ["GNN", "Message-passing neural network"],
    fields: ["AI / ML"],
    families: ["Graph learning", "Representation learning", "Message passing"],
    chapterSlugs: ["11-neural-architectures-attention-ssm-moe-gnn", "40-ai-quantum-cybersecurity-combination-map"],
    summary: "Learn node, edge, or graph representations by repeatedly aggregating information along graph relationships.",
    motivation: "Many systems are relational rather than grid- or sequence-structured.",
    contribution: "GNNs make graph topology part of the inductive bias through differentiable message passing.",
    assumptions: ["The graph structure is meaningful", "Local message passing captures relevant dependencies"],
    complexity: { note: "Typically scales with edges × hidden dimension per message-passing layer." },
    maturity: "Production-proven",
    implementation: ["Choose aggregation invariant to node ordering", "Normalize or gate messages", "Handle batching and sparse adjacency carefully"],
    failureModes: ["Oversmoothing", "Oversquashing", "Long-range dependencies", "Graph construction errors"],
    relations: [{ target: "surface-code-decoding", type: "combines-with", note: "Quantum syndrome/check structure can be represented as a graph for learned decoding components." }],
    tags: ["graph", "message-passing", "representation"],
    openQuestions: ["How can learned graph proposals be combined with exact constrained decoders for safety-critical systems?"],
  },
  {
    id: "diffusion-models",
    name: "Diffusion Models",
    aliases: ["DDPM", "Score-based diffusion"],
    fields: ["AI / ML"],
    families: ["Generative modeling", "Score matching", "Stochastic process"],
    chapterSlugs: ["12-generative-models-diffusion-flow-autoregressive"],
    summary: "Generative models that learn to reverse a progressive noising process or estimate the score of perturbed data distributions.",
    motivation: "Stable likelihood-related training and high sample quality are difficult to achieve simultaneously in some adversarial generative models.",
    contribution: "Diffusion reframes generation as iterative denoising under a well-defined corruption process.",
    assumptions: ["A useful noise schedule/process is specified", "Iterative sampling cost is acceptable or can be accelerated"],
    complexity: { note: "Sampling traditionally requires many denoising evaluations; distillation and improved solvers reduce steps." },
    maturity: "Production-proven",
    implementation: ["Choose forward noise schedule", "Train denoiser/score objective", "Use numerically stable sampler", "Use latent spaces for high-resolution media when appropriate"],
    failureModes: ["Slow sampling", "Training/data bias", "Prompt/conditioning mismatch"],
    relations: [{ target: "flow-matching", type: "alternative-to", note: "Flow matching learns continuous transport dynamics with a different training/sampling formulation." }],
    tags: ["generative", "diffusion", "score"],
    openQuestions: ["How far can few-step or single-step generation go without losing controllability and diversity?"],
  },
  {
    id: "flow-matching",
    name: "Flow Matching",
    aliases: ["Conditional flow matching", "Rectified flow"],
    fields: ["AI / ML"],
    families: ["Generative modeling", "Continuous flows", "Optimal transport"],
    chapterSlugs: ["12-generative-models-diffusion-flow-autoregressive"],
    summary: "Train a vector field that transports a simple base distribution toward the data distribution along chosen probability paths.",
    motivation: "Generative transport can be learned without explicitly simulating the full stochastic reverse process used in conventional diffusion training.",
    contribution: "Flow matching provides a flexible supervised objective for continuous-time generative dynamics and often supports efficient ODE sampling.",
    assumptions: ["A probability path and conditional vector-field target can be sampled"],
    complexity: { note: "Sampling cost depends on ODE solver steps and vector-field evaluation cost." },
    maturity: "Active research",
    implementation: ["Choose coupling/path", "Train conditional vector field", "Integrate ODE at inference", "Measure quality versus number of function evaluations"],
    failureModes: ["Poor path/coupling choice", "Numerical integration error", "High-dimensional stiffness"],
    relations: [{ target: "diffusion-models", type: "alternative-to", note: "Both learn generative dynamics between simple and data distributions." }],
    tags: ["generative", "flow", "ode"],
    openQuestions: ["Which transport paths provide the best quality/compute tradeoff at frontier model scale?"],
  },
  {
    id: "conformal-prediction",
    name: "Conformal Prediction",
    aliases: ["Conformal inference"],
    fields: ["AI / ML"],
    families: ["Uncertainty", "Calibration", "Statistical prediction"],
    chapterSlugs: ["14-uncertainty-causal-active-continual-meta-learning"],
    summary: "Wrap predictions in data-dependent sets or intervals with finite-sample coverage guarantees under exchangeability assumptions.",
    motivation: "Model confidence scores often lack reliable probabilistic calibration, especially across model classes.",
    contribution: "Conformal methods provide distribution-light marginal coverage guarantees using held-out calibration scores.",
    assumptions: ["Calibration and test examples are exchangeable for standard guarantees"],
    complexity: { note: "Usually dominated by model inference plus calibration-score quantile computation." },
    maturity: "Active research",
    implementation: ["Choose nonconformity score", "Reserve calibration data", "Compute finite-sample adjusted quantile", "Return set/interval rather than only a point"],
    failureModes: ["Coverage can degrade under distribution shift", "Marginal coverage may hide subgroup failures", "Prediction sets can be too wide"],
    relations: [{ target: "bayesian-inference", type: "alternative-to", note: "Conformal uncertainty uses calibration rather than requiring a Bayesian posterior." }],
    tags: ["uncertainty", "coverage", "calibration"],
    openQuestions: ["How should conformal guarantees adapt safely to online, dependent, and drifting data?"],
  },
  {
    id: "q-learning",
    name: "Q-Learning",
    aliases: ["Q learning"],
    fields: ["Foundations", "AI / ML"],
    families: ["Reinforcement learning", "Temporal difference", "Control"],
    chapterSlugs: ["05-probabilistic-control-reinforcement-learning"],
    summary: "Off-policy temporal-difference control that learns action values toward a Bellman optimality target.",
    motivation: "Agents need to learn good actions from interaction without requiring a complete environment model.",
    contribution: "Q-learning bootstraps action-value estimates toward reward plus the best estimated future value.",
    assumptions: ["Markov state representation is meaningful", "Sufficient exploration", "Classical convergence assumptions require suitable learning rates and tabular/controlled settings"],
    complexity: { sample: "Environment-dependent; often the dominant cost" },
    maturity: "Established foundation",
    implementation: ["Observe transition", "Compute TD target", "Update selected state-action value", "Use explicit exploration strategy"],
    failureModes: ["Function-approximation instability", "Sparse rewards", "Distribution shift from policy changes", "Overestimation bias"],
    relations: [{ target: "dynamic-programming", type: "derived-from", note: "Q-learning uses a sampled Bellman optimality update rather than full model sweeps." }],
    tags: ["rl", "td", "control"],
    openQuestions: ["How can strong offline priors and online adaptation be combined without unsafe value extrapolation?"],
  },
  {
    id: "grover-search",
    name: "Grover Search",
    aliases: ["Grover's algorithm", "Amplitude amplification"],
    fields: ["Quantum"],
    families: ["Quantum search", "Amplitude amplification"],
    chapterSlugs: ["21-quantum-search-fourier-phase-estimation"],
    summary: "Quantum search that amplifies marked-state amplitude to find an unstructured target using quadratically fewer oracle queries than classical exhaustive search.",
    motivation: "Unstructured search classically requires linear-query effort in the worst case.",
    contribution: "Amplitude amplification gives O(√N) oracle-query complexity for a single marked item.",
    assumptions: ["A coherent reversible oracle marks solutions", "State preparation and repeated oracle use are feasible"],
    complexity: { time: "O(√N) oracle calls", space: "Problem/oracle dependent" },
    maturity: "Established foundation",
    implementation: ["Prepare uniform superposition", "Apply phase oracle", "Apply diffusion/reflection", "Repeat near optimal iteration count", "Measure"],
    failureModes: ["Oracle construction cost erases abstract query advantage", "Unknown number of marked states complicates iteration count", "Fault-tolerant resources can dominate"],
    relations: [{ target: "quantum-phase-estimation", type: "alternative-to", note: "They are distinct core quantum primitives: amplitude amplification versus eigenphase extraction." }],
    tags: ["quantum", "search", "amplitude"],
    openQuestions: ["Which real workloads preserve end-to-end advantage after reversible-oracle and fault-tolerance costs?"],
  },
  {
    id: "quantum-fourier-transform",
    name: "Quantum Fourier Transform",
    aliases: ["QFT"],
    fields: ["Quantum"],
    families: ["Quantum transform", "Fourier methods"],
    chapterSlugs: ["21-quantum-search-fourier-phase-estimation"],
    summary: "Quantum circuit implementing the discrete Fourier transform over amplitudes, used as a subroutine in phase and periodicity algorithms.",
    motivation: "Quantum algorithms can encode global phase/period information into amplitudes that Fourier structure reveals efficiently.",
    contribution: "QFT implements the transform with polynomial-size quantum circuits rather than explicitly materializing all output amplitudes.",
    assumptions: ["Input is coherently encoded in quantum amplitudes", "The desired output is useful through measurement rather than full classical enumeration"],
    complexity: { time: "O(n²) elementary gates for exact n-qubit QFT; approximate variants can be lower" },
    maturity: "Established foundation",
    implementation: ["Hadamard and controlled-phase ladder", "Reverse qubit order or account for bit reversal", "Drop tiny rotations in approximate QFT when justified"],
    failureModes: ["Classical readout cannot expose all amplitudes", "Small rotations are noise-sensitive", "End-to-end advantage depends on surrounding algorithm"],
    relations: [{ target: "quantum-phase-estimation", type: "used-by", note: "Standard QPE uses inverse QFT to decode phase bits." }],
    tags: ["quantum", "fourier", "phase"],
    openQuestions: ["How aggressively can approximate QFT circuits be simplified under realistic logical error budgets?"],
  },
  {
    id: "quantum-phase-estimation",
    name: "Quantum Phase Estimation",
    aliases: ["QPE"],
    fields: ["Quantum"],
    families: ["Eigenvalue estimation", "Quantum primitives"],
    chapterSlugs: ["21-quantum-search-fourier-phase-estimation", "22-quantum-simulation-qsp-qsvt-linear-algebra"],
    summary: "Estimate an eigenphase of a unitary given access to controlled powers of that unitary and a corresponding eigenstate.",
    motivation: "Many quantum simulation and algebra problems reduce to extracting eigenvalues encoded as phases.",
    contribution: "QPE converts coherent phase accumulation into measurable binary estimates and underpins factoring, chemistry, and amplitude methods.",
    assumptions: ["Controlled unitary powers can be implemented", "A state with sufficient eigenstate overlap is available"],
    complexity: { note: "Precision cost scales with controlled evolution depth and desired phase resolution; practical logical-gate cost can be large." },
    maturity: "Established foundation",
    implementation: ["Ancilla/control register", "Controlled U^(2^k)", "Inverse QFT or iterative phase readout", "Measure phase register"],
    failureModes: ["Difficult state preparation", "Deep controlled evolutions", "Precision and fault-tolerance overhead"],
    relations: [
      { target: "quantum-fourier-transform", type: "depends-on", note: "Canonical QPE decodes phase with inverse QFT." },
      { target: "qsvt", type: "alternative-to", note: "Modern block-encoding/QSVT methods can implement many matrix functions without canonical QPE." },
    ],
    tags: ["quantum", "phase", "eigenvalue"],
    openQuestions: ["When do QSVT-style constructions dominate QPE in total fault-tolerant resources?"],
  },
  {
    id: "qsvt",
    name: "Quantum Singular Value Transformation",
    aliases: ["QSVT", "Quantum signal processing"],
    fields: ["Quantum"],
    families: ["Quantum linear algebra", "Polynomial transformation", "Block encoding"],
    chapterSlugs: ["22-quantum-simulation-qsp-qsvt-linear-algebra"],
    summary: "A framework for applying polynomial transformations to singular values of block-encoded operators using controlled quantum signal-processing sequences.",
    motivation: "Many quantum algorithms require implementing functions of matrices or Hamiltonians, not merely estimating a single eigenvalue.",
    contribution: "QSVT provides a unifying polynomial toolkit for Hamiltonian simulation, linear algebra, filtering, and related primitives.",
    assumptions: ["Target operator can be block encoded", "Desired scalar function admits efficient polynomial approximation on the relevant domain"],
    complexity: { note: "Degree of the approximating polynomial largely determines query/gate complexity, plus block-encoding cost." },
    maturity: "Active research",
    implementation: ["Construct block encoding", "Approximate target function by bounded polynomial", "Synthesize phase factors", "Apply alternating signal-processing sequence"],
    failureModes: ["Block encoding is expensive", "High polynomial degree", "Phase synthesis/numerical precision"],
    relations: [{ target: "quantum-phase-estimation", type: "alternative-to", note: "QSVT often replaces explicit eigenvalue readout with direct polynomial operator transformation." }],
    tags: ["quantum", "qsvt", "polynomial"],
    openQuestions: ["Which application-specific block encodings make QSVT end-to-end practical under realistic fault-tolerant costs?"],
  },
  {
    id: "vqe",
    name: "Variational Quantum Eigensolver",
    aliases: ["VQE"],
    fields: ["Quantum"],
    families: ["Variational quantum algorithms", "Quantum chemistry", "Hybrid optimization"],
    chapterSlugs: ["23-quantum-optimization-vqe-qaoa"],
    summary: "Hybrid algorithm that prepares parameterized quantum states and uses a classical optimizer to minimize measured energy expectation.",
    motivation: "Deep fault-tolerant phase estimation may be inaccessible on limited hardware, motivating shorter parameterized circuits.",
    contribution: "VQE turns eigenvalue estimation into a hybrid variational optimization loop suitable for shallow circuits, especially for chemistry prototypes.",
    assumptions: ["Ansatz can represent a useful low-energy state", "Expectation values can be estimated with tolerable sampling noise"],
    complexity: { note: "Measurement/sample cost can dominate; optimization landscape and Hamiltonian term count are central." },
    maturity: "Active research",
    implementation: ["Choose ansatz", "Measure Hamiltonian expectation by grouped terms", "Optimize parameters classically", "Track shot noise and optimizer variance"],
    failureModes: ["Barren plateaus", "Ansatz bias", "Measurement overhead", "Hardware noise"],
    relations: [{ target: "bayesian-optimization", type: "combines-with", note: "BO can tune variational parameters under expensive noisy evaluations." }],
    tags: ["quantum", "variational", "chemistry"],
    openQuestions: ["Where do variational methods remain competitive once error-corrected QPE becomes available?"],
  },
  {
    id: "qaoa",
    name: "Quantum Approximate Optimization Algorithm",
    aliases: ["QAOA"],
    fields: ["Quantum"],
    families: ["Variational quantum algorithms", "Combinatorial optimization"],
    chapterSlugs: ["23-quantum-optimization-vqe-qaoa"],
    summary: "Alternates problem and mixing unitaries with classically optimized parameters to seek high-quality solutions to discrete optimization problems.",
    motivation: "Combinatorial optimization offers a natural target for hybrid quantum-classical algorithms with structured shallow circuits.",
    contribution: "QAOA encodes objective structure into a parameterized quantum circuit whose depth can be increased systematically.",
    assumptions: ["Objective can be mapped to a quantum cost Hamiltonian", "Sampling and classical parameter optimization are feasible"],
    complexity: { note: "Depends on circuit depth p, graph/problem structure, measurement budget, and optimizer behavior." },
    maturity: "Active research",
    implementation: ["Construct cost Hamiltonian", "Alternate cost/mixer unitaries", "Measure objective samples", "Optimize angles"],
    failureModes: ["Parameter concentration or barren regions", "Hardware connectivity overhead", "No practical advantage at small scale"],
    relations: [{ target: "bayesian-optimization", type: "combines-with", note: "BO is one option for expensive noisy parameter tuning." }],
    tags: ["quantum", "optimization", "variational"],
    openQuestions: ["Which problem structures yield robust advantage after compilation and sampling cost?"],
  },
  {
    id: "surface-code-decoding",
    name: "Surface-Code Decoding",
    aliases: ["QEC decoding", "Surface code decoder"],
    fields: ["Quantum", "AI / ML"],
    families: ["Quantum error correction", "Decoding", "Inference"],
    chapterSlugs: ["24-quantum-error-correction-decoding", "25-fault-tolerance-error-mitigation-compilation"],
    summary: "Infer likely physical error chains from repeated syndrome measurements and choose corrections that preserve the encoded logical state.",
    motivation: "Fault-tolerant quantum computation requires correcting noisy physical operations faster and more reliably than logical errors accumulate.",
    contribution: "Surface-code decoders turn sparse syndrome events into correction decisions using graph matching, union-find, belief propagation, tensor methods, or learned approximations.",
    assumptions: ["Syndrome extraction and detector model are available", "Decoder latency fits the control cycle or backlog budget"],
    complexity: { note: "Varies by decoder: matching, union-find, BP, tensor-network, and neural approaches have different latency/accuracy tradeoffs." },
    maturity: "Active research",
    implementation: ["Build detector/error model", "Process syndrome stream", "Infer correction/logical frame update", "Benchmark logical error rate and real-time latency"],
    failureModes: ["Noise-model mismatch", "Decoder latency", "Correlated errors", "Leakage and non-Pauli effects"],
    relations: [
      { target: "graph-neural-networks", type: "combines-with", note: "Graph models can learn priors or decode syndrome graphs." },
      { target: "state-space-models", type: "combines-with", note: "Sequential models can ingest time-correlated syndrome streams." },
    ],
    tags: ["quantum", "qec", "decoder"],
    openQuestions: ["How should learned decoders expose calibrated uncertainty and fall back to exact/conservative methods?"],
  },
  {
    id: "ml-kem",
    name: "ML-KEM",
    aliases: ["Module-Lattice-Based Key-Encapsulation Mechanism", "Kyber-derived KEM"],
    fields: ["Cybersecurity"],
    families: ["Post-quantum cryptography", "Key encapsulation", "Lattices"],
    chapterSlugs: ["31-post-quantum-cryptography"],
    summary: "Standardized module-lattice key-encapsulation mechanism for establishing shared secrets resistant to known classical and quantum attacks under its security assumptions.",
    motivation: "RSA and conventional elliptic-curve key establishment are vulnerable to sufficiently capable quantum computers running Shor-type algorithms.",
    contribution: "ML-KEM provides a standardized practical post-quantum KEM built from module-lattice hardness and efficient polynomial arithmetic.",
    assumptions: ["Module-LWE-related hardness", "Implementations resist side channels and randomness failures"],
    complexity: { note: "Dominated by polynomial/module arithmetic; concrete parameters define bandwidth and CPU cost." },
    maturity: "Production-proven",
    implementation: ["Use standardized parameter sets", "Use constant-time arithmetic", "Use approved randomness", "Apply hybrid migration patterns where ecosystem constraints require them"],
    failureModes: ["Side-channel leakage", "Incorrect decapsulation handling", "Protocol misuse", "Migration interoperability issues"],
    relations: [{ target: "fhe", type: "depends-on", note: "Both use lattice techniques, though their constructions and goals differ." }],
    tags: ["pqc", "kem", "lattice"],
    openQuestions: ["How can large organizations prioritize cryptographic dependency migration under interoperability and lifecycle constraints?"],
  },
  {
    id: "zero-knowledge-proofs",
    name: "Zero-Knowledge Proofs",
    aliases: ["ZKP", "ZK proofs", "zk-SNARK/STARK family"],
    fields: ["Cybersecurity"],
    families: ["Verifiable computation", "Cryptographic proof systems"],
    chapterSlugs: ["32-zero-knowledge-verifiable-computation"],
    summary: "Cryptographic protocols that prove statement validity without revealing the secret witness beyond what validity itself implies.",
    motivation: "Systems often need verifiability without disclosing private data or re-executing expensive computation.",
    contribution: "ZK systems separate proof of correctness from disclosure, enabling privacy-preserving authentication and succinct/verifiable computation.",
    assumptions: ["Security depends on the chosen commitment/hash/pairing assumptions", "Statement is encoded correctly into the proof system"],
    complexity: { note: "Prover/verifier/proof-size costs vary dramatically across Groth16, PLONK-family, STARK/FRI, and recursive systems." },
    maturity: "Production-proven",
    implementation: ["Define arithmetic/constraint representation", "Choose commitment/proof system", "Generate witness", "Prove and verify", "Audit trusted-setup or transparency assumptions"],
    failureModes: ["Circuit specification bugs", "Unsound custom optimizations", "Trusted-setup compromise where applicable", "High prover cost"],
    relations: [{ target: "symbolic-execution", type: "combines-with", note: "Formal analysis can help validate constraints or proof-generating program transformations." }],
    tags: ["zk", "proof", "verification"],
    openQuestions: ["How can proof systems attach compact evidence to adaptive AI-agent actions without prohibitive proving cost?"],
  },
  {
    id: "fhe",
    name: "Fully Homomorphic Encryption",
    aliases: ["FHE", "Homomorphic encryption"],
    fields: ["Cybersecurity", "AI / ML"],
    families: ["Privacy-preserving computation", "Lattice cryptography"],
    chapterSlugs: ["33-mpc-homomorphic-encryption-differential-privacy"],
    summary: "Encryption schemes that support evaluation of general computations on ciphertexts while keeping underlying data encrypted.",
    motivation: "Cloud or collaborative computation may need to process sensitive inputs without learning them in plaintext.",
    contribution: "FHE enables outsourced encrypted computation using noise-managed algebra and bootstrapping or leveled constructions.",
    assumptions: ["Underlying lattice assumptions hold", "Computation can be expressed efficiently in the scheme's arithmetic/Boolean model"],
    complexity: { note: "Orders of magnitude slower than plaintext for many workloads; bootstrapping, ciphertext size, and multiplicative depth are central." },
    maturity: "Active research",
    implementation: ["Select BFV/BGV/CKKS/TFHE-like family based on arithmetic semantics", "Budget multiplicative depth/noise", "Batch/SIMD where possible", "Benchmark end-to-end latency and memory"],
    failureModes: ["Noise overflow", "Incorrect approximate arithmetic", "Massive memory/latency overhead", "Parameter-selection errors"],
    relations: [{ target: "ml-kem", type: "combines-with", note: "Both draw from lattice techniques but serve different cryptographic goals." }],
    tags: ["privacy", "lattice", "encrypted-compute"],
    openQuestions: ["Which AI workloads have enough arithmetic structure to make FHE economically practical at scale?"],
  },
  {
    id: "symbolic-execution",
    name: "Symbolic Execution",
    aliases: ["Symbolic program execution", "Concolic execution"],
    fields: ["Cybersecurity", "Foundations"],
    families: ["Program analysis", "Constraint solving", "Verification"],
    chapterSlugs: ["34-security-analysis-symbolic-execution-fuzzing"],
    summary: "Execute programs over symbolic inputs, accumulating path constraints that solvers can satisfy to generate concrete test cases or prove path properties.",
    motivation: "Random testing struggles to reach branches guarded by precise input conditions.",
    contribution: "Symbolic execution converts program paths into logical constraints, linking execution semantics with SAT/SMT solving.",
    assumptions: ["Program semantics can be modeled", "Path constraints are tractable enough for the solver"],
    complexity: { note: "Path explosion is generally exponential in branching depth; solver complexity can dominate." },
    maturity: "Production-proven",
    implementation: ["Model symbolic state", "Fork on symbolic branches", "Accumulate constraints", "Call SMT solver", "Concretize satisfying inputs"],
    failureModes: ["Path explosion", "Unsupported environment/system calls", "Solver timeouts", "Model divergence from reality"],
    relations: [
      { target: "coverage-guided-fuzzing", type: "combines-with", note: "Concolic execution can generate seeds for branches ordinary fuzzing cannot reach." },
      { target: "zero-knowledge-proofs", type: "combines-with", note: "Formal analysis can validate program constraints used by proof-generating systems." },
    ],
    tags: ["security", "solver", "program-analysis"],
    openQuestions: ["How should neural proposal models prioritize paths without compromising solver-backed correctness?"],
  },
  {
    id: "coverage-guided-fuzzing",
    name: "Coverage-Guided Fuzzing",
    aliases: ["CGF", "Greybox fuzzing"],
    fields: ["Cybersecurity", "AI / ML"],
    families: ["Security testing", "Search", "Adaptive exploration"],
    chapterSlugs: ["34-security-analysis-symbolic-execution-fuzzing", "40-ai-quantum-cybersecurity-combination-map"],
    summary: "Iteratively mutate program inputs and retain mutations that produce novel execution coverage or other useful behavioral signals.",
    motivation: "Pure random fuzzing wastes most executions on inputs that do not explore new program behavior.",
    contribution: "Coverage feedback turns fuzzing into an adaptive search process over input space.",
    assumptions: ["Execution can be instrumented or observed", "Coverage/behavioral novelty correlates with useful vulnerability discovery"],
    complexity: { note: "Dominated by target execution throughput; scheduling and mutation strategy strongly influence effective search." },
    maturity: "Production-proven",
    implementation: ["Maintain corpus", "Mutate selected seeds", "Execute with instrumentation", "Keep novel inputs", "Minimize/reproduce crashes"],
    failureModes: ["Coverage plateaus", "Checksum/magic-value barriers", "Stateful protocols", "Expensive executions"],
    relations: [
      { target: "symbolic-execution", type: "combines-with", note: "Symbolic/concolic techniques can solve difficult branch predicates and seed the fuzzer." },
      { target: "linucb", type: "combines-with", note: "A contextual bandit can adapt mutation/operator selection to program state and historical reward." },
    ],
    tags: ["fuzzing", "security", "coverage"],
    openQuestions: ["Which contextual features best predict mutation/operator value across diverse software targets?"],
  },
];

const byId = new Map(algorithms.map((algorithm) => [algorithm.id, algorithm]));

export function getAlgorithm(id: string) {
  return byId.get(id) ?? null;
}

export function getRelatedAlgorithms(algorithm: AlgorithmEntity) {
  return algorithm.relations
    .map((relation) => ({ relation, algorithm: byId.get(relation.target) }))
    .filter((item): item is { relation: AlgorithmRelation; algorithm: AlgorithmEntity } => Boolean(item.algorithm));
}

export function algorithmsForChapter(slug: string) {
  return algorithms.filter((algorithm) => algorithm.chapterSlugs.includes(slug));
}

export function algorithmSearchText(algorithm: AlgorithmEntity) {
  return [
    algorithm.name,
    ...algorithm.aliases,
    ...algorithm.fields,
    ...algorithm.families,
    algorithm.summary,
    algorithm.motivation,
    algorithm.contribution,
    ...algorithm.tags,
  ]
    .join(" ")
    .toLowerCase();
}
