import type { ResearchCombination } from "@/lib/combinations";

export const combinationAdditions: ResearchCombination[] = [
  {
    id: "private-verifiable-ai",
    title: "FHE × MPC × zero knowledge × AI",
    kicker: "Private verifiable intelligence",
    algorithmIds: ["fhe", "secure-multiparty-computation", "zero-knowledge-proofs", "transformer-attention"],
    motivation: "Cross-organization AI increasingly requires computation over sensitive inputs while also needing evidence that each participant and service followed the intended protocol.",
    hypothesis: "A hybrid architecture can allocate computation among FHE, MPC, and ordinary model execution according to cost/privacy constraints, then attach zero-knowledge proofs to selected protocol steps or outputs so private collaborative AI gains verifiability without centralizing raw data.",
    compatibility: [
      "MPC can combine private inputs held by multiple parties without a single plaintext data pool",
      "FHE can move selected arithmetic to encrypted noninteractive evaluation",
      "Zero-knowledge proofs can attest to protocol or computation properties without revealing the private witness",
      "AI inference/training workloads contain separable layers and operations that can be partitioned across trust boundaries",
    ],
    tensions: [
      "Transformer-style workloads are expensive under both FHE and generic MPC",
      "Hybrid protocol boundaries create conversion and key-management complexity",
      "Proof circuits may not match the arithmetic representation used by the private-computation layer",
      "Privacy guarantees do not prevent leakage through model outputs or repeated queries",
    ],
    expectedBenefits: [
      "No single party needs all raw inputs",
      "Cryptographic evidence can accompany high-value computation steps",
      "Work can be partitioned so expensive cryptography is reserved for sensitive operations",
      "Trust assumptions become explicit and testable",
    ],
    risks: [
      "Latency and bandwidth may make the full design impractical",
      "Protocol composition can introduce subtle security gaps",
      "Incorrect circuit/model transformations can invalidate semantic equivalence",
      "A cryptographically correct pipeline can still produce statistically unsafe or biased outputs",
    ],
    metrics: [
      "End-to-end latency",
      "Communication volume",
      "Ciphertext/proof size",
      "Prover and verifier time",
      "Accuracy drift from private arithmetic approximations",
      "Number and severity of trust assumptions",
    ],
    experimentPlan: [
      "Choose a bounded collaborative inference task with two or more data owners",
      "Partition the model into plaintext-safe, MPC-suitable, and FHE-suitable operations",
      "Implement a plaintext functional baseline",
      "Add private computation incrementally and measure cost after every boundary",
      "Attach a proof to one security-critical transformation or output property rather than proving the entire model initially",
      "Threat-model malicious and semi-honest participants separately",
      "Compare against simpler MPC-only and FHE-only baselines",
    ],
    sourceChapters: [
      "11-neural-architectures-attention-ssm-moe-gnn",
      "32-zero-knowledge-verifiable-computation",
      "33-mpc-homomorphic-encryption-differential-privacy",
      "40-ai-quantum-cybersecurity-combination-map",
    ],
    status: "Hypothesis",
  },
  {
    id: "learned-exact-search",
    title: "Learned heuristics × A* × branch and bound",
    kicker: "Learning-guided exact search",
    algorithmIds: ["learned-heuristics", "a-star", "branch-and-bound"],
    motivation: "Exact search procedures provide correctness guarantees but can spend most of their time exploring low-value states or branches; learned models can recognize structure from previously solved instances but are not inherently trustworthy enough to replace exact reasoning.",
    hypothesis: "Use learned models only to prioritize expansion, branching, incumbent proposals, or optional bounded heuristics while retaining admissible A* criteria or branch-and-bound bounds as the correctness boundary. This can reduce search work without turning the solver into an opaque approximate predictor.",
    compatibility: [
      "A* already separates path cost from heuristic guidance",
      "Branch-and-bound already separates exact pruning bounds from node-ordering policy",
      "Solved search traces provide supervised/self-generated data for learning priorities",
      "The classical solver can verify candidate solutions and bounds independently of the learned model",
    ],
    tensions: [
      "Fast but overconfident learned guidance can concentrate search in the wrong region",
      "Guarantee-preserving constraints may limit the apparent speedup of the learned heuristic",
      "Inference latency can dominate lightweight search nodes",
      "Training distribution and instance distribution can differ substantially",
    ],
    expectedBenefits: [
      "Earlier discovery of strong incumbents",
      "Fewer expanded nodes",
      "Better branch ordering",
      "Preserved exactness when learned outputs affect ordering but not validity of bounds",
    ],
    risks: [
      "Hidden loss of optimality if learned scores leak into pruning rules incorrectly",
      "Solver/model co-adaptation overfits benchmark families",
      "GPU/accelerator inference overhead can make wall-clock time worse despite fewer nodes",
      "Reproducibility becomes harder if learned policies are stochastic",
    ],
    metrics: [
      "Wall-clock solve time",
      "Nodes expanded",
      "Time to first incumbent",
      "Optimality gap over time",
      "Fraction of instances solved within budget",
      "Model inference overhead",
    ],
    experimentPlan: [
      "Choose an optimization/search domain with a strong classical baseline",
      "Collect branch/state traces from the baseline solver",
      "Train separate models for node ordering and bound/value prediction",
      "First allow the learned model to alter ordering only, preserving exact pruning rules",
      "Compare against hand-designed heuristics and random/standard ordering",
      "Add bounded learned heuristic influence only after verifying exactness or explicit suboptimality guarantees",
      "Evaluate both node reduction and total wall-clock cost on out-of-distribution instances",
    ],
    sourceChapters: [
      "02-search-graphs-ordering-indexing",
      "03-optimization-randomization-constraints",
      "09-combination-research-map",
      "40-ai-quantum-cybersecurity-combination-map",
    ],
    status: "Prototype candidate",
  },
];
