import type { ImplementationRecord } from "./implementations.ts";

/**
 * Foundational implementation records added after the original monolithic
 * registry was established. Keeping new records modular avoids growing the
 * historical catalog indefinitely while preserving one exported registry.
 */
export const foundationImplementationAdditions: ImplementationRecord[] = [
  {
    id: "statsmodels-kalman-filter",
    name: "statsmodels Kalman Filter",
    repository: "https://github.com/statsmodels/statsmodels",
    homepage: "https://www.statsmodels.org/",
    algorithmIds: ["kalman-filter"],
    language: "Python / Cython",
    interfaces: ["Python API", "statsmodels.tsa.statespace.KalmanFilter", "State-space models"],
    license: "BSD-style (3-clause form in repository LICENSE.txt)",
    maturity: "Production-proven",
    summary: "statsmodels exposes a configurable KalmanFilter for linear state-space time-series models, backed by optimized state-space filtering machinery.",
    implementationNotes: [
      "The inspected Python state-space filter defines conventional Kalman filtering together with configurable inversion, stability, timing, and memory modes.",
      "The implementation explicitly tracks predicted and filtered state means/covariances, forecast-error covariance, and Kalman gain outputs used by the recursive estimator.",
      "This executable record demonstrates a mature state-space implementation; the separate Kalman 1960 Reference remains the primary method source.",
    ],
    sourcePaths: [
      { label: "KalmanFilter state-space implementation", url: "https://github.com/statsmodels/statsmodels/blob/cc001c25997351ecbd0b04d2968a08106a04a71f/statsmodels/tsa/statespace/kalman_filter.py" },
      { label: "Repository license", url: "https://github.com/statsmodels/statsmodels/blob/cc001c25997351ecbd0b04d2968a08106a04a71f/LICENSE.txt" },
    ],
    verifiedRef: "main",
    verifiedCommit: "cc001c25997351ecbd0b04d2968a08106a04a71f",
    lastVerified: "2026-10-03",
  },
  {
    id: "diffprivlib-laplace",
    name: "IBM diffprivlib Laplace mechanism",
    repository: "https://github.com/IBM/differential-privacy-library",
    homepage: "https://diffprivlib.readthedocs.io/",
    algorithmIds: ["differential-privacy"],
    language: "Python",
    interfaces: ["Python API", "diffprivlib.mechanisms.Laplace"],
    license: "MIT",
    maturity: "Established open-source",
    summary: "IBM diffprivlib provides an executable classical Laplace mechanism and related bounded/truncated variants for differential-privacy workflows.",
    implementationNotes: [
      "The inspected Laplace mechanism accepts epsilon, delta, and sensitivity explicitly and derives the randomization scale from those privacy/sensitivity parameters.",
      "The source directly cites the Dwork–McSherry–Nissim–Smith sensitivity-calibration work curated separately as the archive's primary differential-privacy reference.",
      "The implementation uses a multi-uniform Laplace sampler intended to reduce floating-point reconstruction risks; that implementation detail is evidence about this library, not part of the archive's generic Laplace-mechanism claim.",
    ],
    sourcePaths: [
      { label: "Laplace mechanism implementation", url: "https://github.com/IBM/differential-privacy-library/blob/f9a37dd74b18108d46a421e66321635a3d774eab/diffprivlib/mechanisms/laplace.py" },
      { label: "Repository license", url: "https://github.com/IBM/differential-privacy-library/blob/f9a37dd74b18108d46a421e66321635a3d774eab/LICENSE.md" },
    ],
    verifiedRef: "main",
    verifiedCommit: "f9a37dd74b18108d46a421e66321635a3d774eab",
    lastVerified: "2026-10-03",
  },
  {
    id: "qiskit-qft",
    name: "Qiskit Quantum Fourier Transform",
    repository: "https://github.com/Qiskit/qiskit",
    homepage: "https://www.ibm.com/quantum/qiskit",
    algorithmIds: ["quantum-fourier-transform"],
    language: "Python",
    interfaces: ["Python SDK", "QFTGate", "synth_qft_full"],
    license: "Apache-2.0",
    maturity: "Established open-source",
    summary: "Qiskit's circuit library provides a Quantum Fourier Transform gate/circuit together with exact, inverse, and approximate synthesis controls.",
    implementationNotes: [
      "The inspected source defines the QFT unitary, QFTGate, inverse-QFT behavior, and synthesis through Hadamard/controlled-phase/swap structure.",
      "Approximate QFT support drops the smallest controlled-phase rotations through an explicit approximation degree, making the implementation useful for studying depth/accuracy tradeoffs.",
      "The legacy QFT BlueprintCircuit class is marked for Qiskit 3.0 removal in favor of QFTGate or synth_qft_full, so this record points to the source that exposes both the deprecated wrapper and the retained gate/synthesis direction rather than presenting the deprecated class as the long-term API.",
    ],
    sourcePaths: [
      { label: "QFT circuit and QFTGate", url: "https://github.com/Qiskit/qiskit/blob/a1c2c2e796ff265c59a916c49d09942b27eb0e28/qiskit/circuit/library/basis_change/qft.py" },
    ],
    verifiedRef: "main",
    verifiedCommit: "a1c2c2e796ff265c59a916c49d09942b27eb0e28",
    lastVerified: "2026-10-03",
  },
  {
    id: "botorch-bayesian-optimization",
    name: "BoTorch Bayesian Optimization",
    repository: "https://github.com/meta-pytorch/botorch",
    homepage: "https://botorch.org/",
    algorithmIds: ["bayesian-optimization"],
    language: "Python",
    interfaces: ["Python API", "Gaussian-process models", "Expected/Log Expected Improvement", "Acquisition optimization"],
    license: "MIT",
    maturity: "Production-proven",
    summary: "BoTorch provides modular probabilistic models and acquisition functions for modern Bayesian-optimization workflows on PyTorch.",
    implementationNotes: [
      "The inspected analytic acquisition module evaluates model posteriors and implements Probability of Improvement, Expected Improvement, and numerically stable Log Expected Improvement for Gaussian posterior settings.",
      "The implementation makes the surrogate-posterior-to-acquisition step explicit, providing executable evidence for the archive's probabilistic-surrogate view of Bayesian optimization.",
      "BoTorch contains many additional Monte-Carlo, constrained, multi-objective, and batch acquisition methods; this registry record deliberately anchors only the directly inspected analytic acquisition surface rather than claiming exhaustive coverage of the package.",
    ],
    sourcePaths: [
      { label: "Analytic acquisition functions", url: "https://github.com/meta-pytorch/botorch/blob/bda063ae5c6d2bbe058a7d1566818ae2e14a673e/botorch/acquisition/analytic.py" },
      { label: "Repository license", url: "https://github.com/meta-pytorch/botorch/blob/bda063ae5c6d2bbe058a7d1566818ae2e14a673e/LICENSE" },
    ],
    verifiedRef: "main",
    verifiedCommit: "bda063ae5c6d2bbe058a7d1566818ae2e14a673e",
    lastVerified: "2026-10-03",
  },
  {
    id: "pymatching-surface-code-decoder",
    name: "PyMatching MWPM decoder",
    repository: "https://github.com/oscarhiggott/PyMatching",
    homepage: "https://pymatching.readthedocs.io/",
    algorithmIds: ["surface-code-decoding"],
    language: "Python / C++",
    interfaces: ["Python API", "pymatching.Matching", "Stim DetectorErrorModel", "Minimum-weight perfect matching"],
    license: "Apache-2.0",
    maturity: "Established open-source",
    summary: "PyMatching provides minimum-weight-perfect-matching decoding for detector/syndrome graphs, including repeated noisy measurement rounds and Stim detector-error-model integration used in surface-code workflows.",
    implementationNotes: [
      "The inspected Matching API explicitly constructs matching graphs and decodes them with minimum-weight perfect matching from parity-check matrices, graph objects, or Stim detector error models.",
      "Repeated stabilizer measurements are represented through repetitions and timelike edge weights/probabilities, making the implementation directly relevant to the archive's spacetime surface-code decoding Claim.",
      "The pinned repository also contains a C++ sparse-blossom MWPM decoding driver and committed surface-code benchmark assets; this executable record does not treat those benchmarks as independent evidence for universal decoder performance.",
    ],
    sourcePaths: [
      { label: "Matching Python API", url: "https://github.com/oscarhiggott/PyMatching/blob/6f63b2b9474ba0fa7e511fe52bffdce858a06984/src/pymatching/matching.py" },
      { label: "Sparse-blossom MWPM decoder", url: "https://github.com/oscarhiggott/PyMatching/blob/6f63b2b9474ba0fa7e511fe52bffdce858a06984/src/pymatching/sparse_blossom/driver/mwpm_decoding.cc" },
      { label: "Surface-code benchmarks", url: "https://github.com/oscarhiggott/PyMatching/blob/6f63b2b9474ba0fa7e511fe52bffdce858a06984/benchmarks/surface_codes/README.md" },
      { label: "Repository license", url: "https://github.com/oscarhiggott/PyMatching/blob/6f63b2b9474ba0fa7e511fe52bffdce858a06984/LICENSE" },
    ],
    verifiedRef: "master",
    verifiedCommit: "6f63b2b9474ba0fa7e511fe52bffdce858a06984",
    lastVerified: "2026-10-03",
  },
  {
    id: "klee-symbolic-execution",
    name: "KLEE symbolic execution engine",
    repository: "https://github.com/klee/klee",
    homepage: "https://klee-se.org/",
    algorithmIds: ["symbolic-execution"],
    language: "C++",
    interfaces: ["LLVM bitcode", "klee command-line", "Solver-backed symbolic execution"],
    license: "University of Illinois/NCSA Open Source License",
    maturity: "Established open-source",
    summary: "KLEE provides an executable symbolic virtual machine for LLVM bitcode, maintaining path constraints and solver-backed branch exploration to generate concrete test cases and analyze program behavior.",
    implementationNotes: [
      "At the verified revision, Executor::fork evaluates a symbolic branch condition against the current execution state's constraint set through the configured solver before deciding whether one or both paths remain feasible.",
      "When KLEE explores a branch, the executor adds the corresponding condition or its negation to the child state's constraint set, directly exposing the path-constraint mechanism represented by the archive's symbolic-execution Algorithm and Claim.",
      "The executor also supports concretization and resource controls when solver/fork budgets are exceeded; this record documents the inspected KLEE implementation rather than treating those engineering policies as universal symbolic-execution semantics.",
    ],
    sourcePaths: [
      { label: "Core symbolic executor", url: "https://github.com/klee/klee/blob/9a36a6782b814fe1fa37439652b875114faa0e20/lib/Core/Executor.cpp" },
      { label: "Repository license", url: "https://github.com/klee/klee/blob/9a36a6782b814fe1fa37439652b875114faa0e20/LICENSE.TXT" },
    ],
    verifiedRef: "master",
    verifiedCommit: "9a36a6782b814fe1fa37439652b875114faa0e20",
    lastVerified: "2026-10-04",
  },
  {
    id: "mp-spdz-secure-mpc",
    name: "MP-SPDZ secure multiparty computation",
    repository: "https://github.com/data61/MP-SPDZ",
    homepage: "https://mp-spdz.readthedocs.io/",
    algorithmIds: ["secure-multiparty-computation"],
    language: "C++ / Python",
    interfaces: ["MPC compiler", "Protocol runtimes", "Secret sharing", "Beaver-triple arithmetic"],
    license: "BSD-3-Clause (primary repository license; bundled components retain their listed licenses)",
    maturity: "Established open-source",
    summary: "MP-SPDZ is a multi-protocol secure-computation framework covering multiple corruption assumptions and MPC techniques, including secret sharing, homomorphic encryption, and garbled circuits.",
    implementationNotes: [
      "The pinned README explicitly describes honest- and dishonest-majority, passive/semi-honest, and malicious/active security-model support, so this record treats MP-SPDZ as a multi-protocol implementation rather than collapsing those models into one guarantee.",
      "The inspected Semi protocol is an explicit dishonest-majority arithmetic protocol modulo a power of two and inherits Beaver-triple multiplication machinery.",
      "Beaver::prepare_mul masks the two secret-shared multiplicands with a preprocessing triple, exchange opens the masked differences through the configured MAC/opening layer, and finalize_mul reconstructs the product share from the triple and opened masks. This is executable evidence for one MPC arithmetic path, not a claim that every MP-SPDZ protocol has identical trust, preprocessing, or corruption assumptions.",
    ],
    sourcePaths: [
      { label: "Framework scope and protocol models", url: "https://github.com/data61/MP-SPDZ/blob/d39bd91c08801cb195012d6df5267eac3a9c5ef1/README.md" },
      { label: "Semi dishonest-majority protocol", url: "https://github.com/data61/MP-SPDZ/blob/d39bd91c08801cb195012d6df5267eac3a9c5ef1/Protocols/Semi.h" },
      { label: "Beaver multiplication implementation", url: "https://github.com/data61/MP-SPDZ/blob/d39bd91c08801cb195012d6df5267eac3a9c5ef1/Protocols/Beaver.hpp" },
      { label: "Repository license", url: "https://github.com/data61/MP-SPDZ/blob/d39bd91c08801cb195012d6df5267eac3a9c5ef1/License.txt" },
    ],
    verifiedRef: "master",
    verifiedCommit: "d39bd91c08801cb195012d6df5267eac3a9c5ef1",
    lastVerified: "2026-10-04",
  },
  {
    id: "openfhe-ckks-bootstrapping",
    name: "OpenFHE CKKS bootstrapping",
    repository: "https://github.com/openfheorg/openfhe-development",
    homepage: "https://openfhe.org/",
    algorithmIds: ["fhe"],
    language: "C++",
    interfaces: ["C++ API", "CKKS", "EvalBootstrap", "Bootstrapping evaluation keys"],
    license: "BSD-2-Clause",
    maturity: "Established open-source",
    summary: "OpenFHE is an open-source fully homomorphic encryption library; this record anchors its CKKS approximate-bootstrapping path as executable evidence for encrypted computation with ciphertext refresh.",
    implementationNotes: [
      "The pinned README identifies OpenFHE as an FHE library spanning BFV, BGV, CKKS, and FHEW/TFHE-family capabilities; this record deliberately scopes the inspected executable path to CKKS approximate bootstrapping rather than treating every supported scheme as identical.",
      "The inspected simple CKKS example enables FHE, configures bootstrap depth, generates bootstrap evaluation keys, constructs a deliberately depleted ciphertext, and calls EvalBootstrap with the stated goal of increasing the levels remaining for further homomorphic computation.",
      "The concrete FHECKKSRNS::EvalBootstrap implementation and setup logic expose the modern CKKS refresh machinery and its parameter restrictions. This is implementation evidence for a current lattice-FHE path, not a claim that OpenFHE reproduces Gentry's 2009 ideal-lattice construction or that every FHE scheme uses the same bootstrapping mechanism.",
    ],
    sourcePaths: [
      { label: "OpenFHE scope and supported FHE schemes", url: "https://github.com/openfheorg/openfhe-development/blob/6206d24f9eefefc620b524a4f2b9f308feb91e9f/README.md" },
      { label: "Simple CKKS bootstrapping example", url: "https://github.com/openfheorg/openfhe-development/blob/6206d24f9eefefc620b524a4f2b9f308feb91e9f/src/pke/examples/simple-ckks-bootstrapping.cpp" },
      { label: "CKKS bootstrapping implementation", url: "https://github.com/openfheorg/openfhe-development/blob/6206d24f9eefefc620b524a4f2b9f308feb91e9f/src/pke/lib/scheme/ckksrns/ckksrns-fhe.cpp" },
      { label: "Repository license", url: "https://github.com/openfheorg/openfhe-development/blob/6206d24f9eefefc620b524a4f2b9f308feb91e9f/LICENSE" },
    ],
    verifiedRef: "main",
    verifiedCommit: "6206d24f9eefefc620b524a4f2b9f308feb91e9f",
    lastVerified: "2026-10-04",
  },
];
