import type { ImplementationRecord } from "./implementations.ts";

/**
 * Foundational implementation records added after the original monolithic
 * registry was established. Keeping new records modular avoids growing the
 * historical catalog indefinitely while preserving one exported registry.
 */
export const foundationImplementationAdditions: ImplementationRecord[] = [
  {
    id: "statsmodels-kalman-filter",
    name: "statsmodels Kalman Filter",
    repository: "https://github.com/statsmodels/statsmodels",
    homepage: "https://www.statsmodels.org/",
    algorithmIds: ["kalman-filter"],
    language: "Python / Cython",
    interfaces: ["Python API", "statsmodels.tsa.statespace.KalmanFilter", "State-space models"],
    license: "BSD-style (3-clause form in repository LICENSE.txt)",
    maturity: "Production-proven",
    summary: "statsmodels exposes a configurable KalmanFilter for linear state-space time-series models, backed by optimized state-space filtering machinery.",
    implementationNotes: [
      "The inspected Python state-space filter defines conventional Kalman filtering together with configurable inversion, stability, timing, and memory modes.",
      "The implementation explicitly tracks predicted and filtered state means/covariances, forecast-error covariance, and Kalman gain outputs used by the recursive estimator.",
      "This executable record demonstrates a mature state-space implementation; the separate Kalman 1960 Reference remains the primary method source.",
    ],
    sourcePaths: [
      { label: "KalmanFilter state-space implementation", url: "https://github.com/statsmodels/statsmodels/blob/cc001c25997351ecbd0b04d2968a08106a04a71f/statsmodels/tsa/statespace/kalman_filter.py" },
      { label: "Repository license", url: "https://github.com/statsmodels/statsmodels/blob/cc001c25997351ecbd0b04d2968a08106a04a71f/LICENSE.txt" },
    ],
    verifiedRef: "main",
    verifiedCommit: "cc001c25997351ecbd0b04d2968a08106a04a71f",
    lastVerified: "2026-10-03",
  },
  {
    id: "diffprivlib-laplace",
    name: "IBM diffprivlib Laplace mechanism",
    repository: "https://github.com/IBM/differential-privacy-library",
    homepage: "https://diffprivlib.readthedocs.io/",
    algorithmIds: ["differential-privacy"],
    language: "Python",
    interfaces: ["Python API", "diffprivlib.mechanisms.Laplace"],
    license: "MIT",
    maturity: "Established open-source",
    summary: "IBM diffprivlib provides an executable classical Laplace mechanism and related bounded/truncated variants for differential-privacy workflows.",
    implementationNotes: [
      "The inspected Laplace mechanism accepts epsilon, delta, and sensitivity explicitly and derives the randomization scale from those privacy/sensitivity parameters.",
      "The source directly cites the Dwork–McSherry–Nissim–Smith sensitivity-calibration work curated separately as the archive's primary differential-privacy reference.",
      "The implementation uses a multi-uniform Laplace sampler intended to reduce floating-point reconstruction risks; that implementation detail is evidence about this library, not part of the archive's generic Laplace-mechanism claim.",
    ],
    sourcePaths: [
      { label: "Laplace mechanism implementation", url: "https://github.com/IBM/differential-privacy-library/blob/f9a37dd74b18108d46a421e66321635a3d774eab/diffprivlib/mechanisms/laplace.py" },
      { label: "Repository license", url: "https://github.com/IBM/differential-privacy-library/blob/f9a37dd74b18108d46a421e66321635a3d774eab/LICENSE.md" },
    ],
    verifiedRef: "main",
    verifiedCommit: "f9a37dd74b18108d46a421e66321635a3d774eab",
    lastVerified: "2026-10-03",
  },
  {
    id: "qiskit-qft",
    name: "Qiskit Quantum Fourier Transform",
    repository: "https://github.com/Qiskit/qiskit",
    homepage: "https://www.ibm.com/quantum/qiskit",
    algorithmIds: ["quantum-fourier-transform"],
    language: "Python",
    interfaces: ["Python SDK", "QFTGate", "synth_qft_full"],
    license: "Apache-2.0",
    maturity: "Established open-source",
    summary: "Qiskit's circuit library provides a Quantum Fourier Transform gate/circuit together with exact, inverse, and approximate synthesis controls.",
    implementationNotes: [
      "The inspected source defines the QFT unitary, QFTGate, inverse-QFT behavior, and synthesis through Hadamard/controlled-phase/swap structure.",
      "Approximate QFT support drops the smallest controlled-phase rotations through an explicit approximation degree, making the implementation useful for studying depth/accuracy tradeoffs.",
      "The legacy QFT BlueprintCircuit class is marked for Qiskit 3.0 removal in favor of QFTGate or synth_qft_full, so this record points to the source that exposes both the deprecated wrapper and the retained gate/synthesis direction rather than presenting the deprecated class as the long-term API.",
    ],
    sourcePaths: [
      { label: "QFT circuit and QFTGate", url: "https://github.com/Qiskit/qiskit/blob/a1c2c2e796ff265c59a916c49d09942b27eb0e28/qiskit/circuit/library/basis_change/qft.py" },
    ],
    verifiedRef: "main",
    verifiedCommit: "a1c2c2e796ff265c59a916c49d09942b27eb0e28",
    lastVerified: "2026-10-03",
  },
  {
    id: "botorch-bayesian-optimization",
    name: "BoTorch Bayesian Optimization",
    repository: "https://github.com/meta-pytorch/botorch",
    homepage: "https://botorch.org/",
    algorithmIds: ["bayesian-optimization"],
    language: "Python",
    interfaces: ["Python API", "Gaussian-process models", "Expected/Log Expected Improvement", "Acquisition optimization"],
    license: "MIT",
    maturity: "Production-proven",
    summary: "BoTorch provides modular probabilistic models and acquisition functions for modern Bayesian-optimization workflows on PyTorch.",
    implementationNotes: [
      "The inspected analytic acquisition module evaluates model posteriors and implements Probability of Improvement, Expected Improvement, and numerically stable Log Expected Improvement for Gaussian posterior settings.",
      "The implementation makes the surrogate-posterior-to-acquisition step explicit, providing executable evidence for the archive's probabilistic-surrogate view of Bayesian optimization.",
      "BoTorch contains many additional Monte-Carlo, constrained, multi-objective, and batch acquisition methods; this registry record deliberately anchors only the directly inspected analytic acquisition surface rather than claiming exhaustive coverage of the package.",
    ],
    sourcePaths: [
      { label: "Analytic acquisition functions", url: "https://github.com/meta-pytorch/botorch/blob/bda063ae5c6d2bbe058a7d1566818ae2e14a673e/botorch/acquisition/analytic.py" },
      { label: "Repository license", url: "https://github.com/meta-pytorch/botorch/blob/bda063ae5c6d2bbe058a7d1566818ae2e14a673e/LICENSE" },
    ],
    verifiedRef: "main",
    verifiedCommit: "bda063ae5c6d2bbe058a7d1566818ae2e14a673e",
    lastVerified: "2026-10-03",
  },
  {
    id: "pymatching-surface-code-decoder",
    name: "PyMatching MWPM decoder",
    repository: "https://github.com/oscarhiggott/PyMatching",
    homepage: "https://pymatching.readthedocs.io/",
    algorithmIds: ["surface-code-decoding"],
    language: "Python / C++",
    interfaces: ["Python API", "pymatching.Matching", "Stim DetectorErrorModel", "Minimum-weight perfect matching"],
    license: "Apache-2.0",
    maturity: "Established open-source",
    summary: "PyMatching provides minimum-weight-perfect-matching decoding for detector/syndrome graphs, including repeated noisy measurement rounds and Stim detector-error-model integration used in surface-code workflows.",
    implementationNotes: [
      "The inspected Matching API explicitly constructs matching graphs and decodes them with minimum-weight perfect matching from parity-check matrices, graph objects, or Stim detector error models.",
      "Repeated stabilizer measurements are represented through repetitions and timelike edge weights/probabilities, making the implementation directly relevant to the archive's spacetime surface-code decoding Claim.",
      "The pinned repository also contains a C++ sparse-blossom MWPM decoding driver and committed surface-code benchmark assets; this executable record does not treat those benchmarks as independent evidence for universal decoder performance.",
    ],
    sourcePaths: [
      { label: "Matching Python API", url: "https://github.com/oscarhiggott/PyMatching/blob/6f63b2b9474ba0fa7e511fe52bffdce858a06984/src/pymatching/matching.py" },
      { label: "Sparse-blossom MWPM decoder", url: "https://github.com/oscarhiggott/PyMatching/blob/6f63b2b9474ba0fa7e511fe52bffdce858a06984/src/pymatching/sparse_blossom/driver/mwpm_decoding.cc" },
      { label: "Surface-code benchmarks", url: "https://github.com/oscarhiggott/PyMatching/blob/6f63b2b9474ba0fa7e511fe52bffdce858a06984/benchmarks/surface_codes/README.md" },
      { label: "Repository license", url: "https://github.com/oscarhiggott/PyMatching/blob/6f63b2b9474ba0fa7e511fe52bffdce858a06984/LICENSE" },
    ],
    verifiedRef: "master",
    verifiedCommit: "6f63b2b9474ba0fa7e511fe52bffdce858a06984",
    lastVerified: "2026-10-03",
  },
  {
    id: "klee-symbolic-execution",
    name: "KLEE symbolic execution engine",
    repository: "https://github.com/klee/klee",
    homepage: "https://klee-se.org/",
    algorithmIds: ["symbolic-execution"],
    language: "C++",
    interfaces: ["LLVM bitcode", "klee command-line", "Solver-backed symbolic execution"],
    license: "University of Illinois/NCSA Open Source License",
    maturity: "Established open-source",
    summary: "KLEE provides an executable symbolic virtual machine for LLVM bitcode, maintaining path constraints and solver-backed branch exploration to generate concrete test cases and analyze program behavior.",
    implementationNotes: [
      "At the verified revision, Executor::fork evaluates a symbolic branch condition against the current execution state's constraint set through the configured solver before deciding whether one or both paths remain feasible.",
      "When KLEE explores a branch, the executor adds the corresponding condition or its negation to the child state's constraint set, directly exposing the path-constraint mechanism represented by the archive's symbolic-execution Algorithm and Claim.",
      "The executor also supports concretization and resource controls when solver/fork budgets are exceeded; this record documents the inspected KLEE implementation rather than treating those engineering policies as universal symbolic-execution semantics.",
    ],
    sourcePaths: [
      { label: "Core symbolic executor", url: "https://github.com/klee/klee/blob/9a36a6782b814fe1fa37439652b875114faa0e20/lib/Core/Executor.cpp" },
      { label: "Repository license", url: "https://github.com/klee/klee/blob/9a36a6782b814fe1fa37439652b875114faa0e20/LICENSE.TXT" },
    ],
    verifiedRef: "master",
    verifiedCommit: "9a36a6782b814fe1fa37439652b875114faa0e20",
    lastVerified: "2026-10-04",
  },
  {
    id: "mp-spdz-secure-mpc",
    name: "MP-SPDZ secure multiparty computation",
    repository: "https://github.com/data61/MP-SPDZ",
    homepage: "https://mp-spdz.readthedocs.io/",
    algorithmIds: ["secure-multiparty-computation"],
    language: "C++ / Python",
    interfaces: ["MPC compiler", "Protocol runtimes", "Secret sharing", "Beaver-triple arithmetic"],
    license: "BSD-3-Clause (primary repository license; bundled components retain their listed licenses)",
    maturity: "Established open-source",
    summary: "MP-SPDZ is a multi-protocol secure-computation framework covering multiple corruption assumptions and MPC techniques, including secret sharing, homomorphic encryption, and garbled circuits.",
    implementationNotes: [
      "The pinned README explicitly describes honest- and dishonest-majority, passive/semi-honest, and malicious/active security-model support, so this record treats MP-SPDZ as a multi-protocol implementation rather than collapsing those models into one guarantee.",
      "The inspected Semi protocol is an explicit dishonest-majority arithmetic protocol modulo a power of two and inherits Beaver-triple multiplication machinery.",
      "Beaver::prepare_mul masks the two secret-shared multiplicands with a preprocessing triple, exchange opens the masked differences through the configured MAC/opening layer, and finalize_mul reconstructs the product share from the triple and opened masks. This is executable evidence for one MPC arithmetic path, not a claim that every MP-SPDZ protocol has identical trust, preprocessing, or corruption assumptions.",
    ],
    sourcePaths: [
      { label: "Framework scope and protocol models", url: "https://github.com/data61/MP-SPDZ/blob/d39bd91c08801cb195012d6df5267eac3a9c5ef1/README.md" },
      { label: "Semi dishonest-majority protocol", url: "https://github.com/data61/MP-SPDZ/blob/d39bd91c08801cb195012d6df5267eac3a9c5ef1/Protocols/Semi.h" },
      { label: "Beaver multiplication implementation", url: "https://github.com/data61/MP-SPDZ/blob/d39bd91c08801cb195012d6df5267eac3a9c5ef1/Protocols/Beaver.hpp" },
      { label: "Repository license", url: "https://github.com/data61/MP-SPDZ/blob/d39bd91c08801cb195012d6df5267eac3a9c5ef1/License.txt" },
    ],
    verifiedRef: "master",
    verifiedCommit: "d39bd91c08801cb195012d6df5267eac3a9c5ef1",
    lastVerified: "2026-10-04",
  },
  {
    id: "openfhe-ckks-bootstrapping",
    name: "OpenFHE CKKS bootstrapping",
    repository: "https://github.com/openfheorg/openfhe-development",
    homepage: "https://openfhe.org/",
    algorithmIds: ["fhe"],
    language: "C++",
    interfaces: ["C++ API", "CKKS", "EvalBootstrap", "Bootstrapping evaluation keys"],
    license: "BSD-2-Clause",
    maturity: "Established open-source",
    summary: "OpenFHE is an open-source fully homomorphic encryption library; this record anchors its CKKS approximate-bootstrapping path as executable evidence for encrypted computation with ciphertext refresh.",
    implementationNotes: [
      "The pinned README identifies OpenFHE as an FHE library spanning BFV, BGV, CKKS, and FHEW/TFHE-family capabilities; this record deliberately scopes the inspected executable path to CKKS approximate bootstrapping rather than treating every supported scheme as identical.",
      "The inspected simple CKKS example enables FHE, configures bootstrap depth, generates bootstrap evaluation keys, constructs a deliberately depleted ciphertext, and calls EvalBootstrap with the stated goal of increasing the levels remaining for further homomorphic computation.",
      "The concrete FHECKKSRNS::EvalBootstrap implementation and setup logic expose the modern CKKS refresh machinery and its parameter restrictions. This is implementation evidence for a current lattice-FHE path, not a claim that OpenFHE reproduces Gentry's 2009 ideal-lattice construction or that every FHE scheme uses the same bootstrapping mechanism.",
    ],
    sourcePaths: [
      { label: "OpenFHE scope and supported FHE schemes", url: "https://github.com/openfheorg/openfhe-development/blob/6206d24f9eefefc620b524a4f2b9f308feb91e9f/README.md" },
      { label: "Simple CKKS bootstrapping example", url: "https://github.com/openfheorg/openfhe-development/blob/6206d24f9eefefc620b524a4f2b9f308feb91e9f/src/pke/examples/simple-ckks-bootstrapping.cpp" },
      { label: "CKKS bootstrapping implementation", url: "https://github.com/openfheorg/openfhe-development/blob/6206d24f9eefefc620b524a4f2b9f308feb91e9f/src/pke/lib/scheme/ckksrns/ckksrns-fhe.cpp" },
      { label: "Repository license", url: "https://github.com/openfheorg/openfhe-development/blob/6206d24f9eefefc620b524a4f2b9f308feb91e9f/LICENSE" },
    ],
    verifiedRef: "main",
    verifiedCommit: "6206d24f9eefefc620b524a4f2b9f308feb91e9f",
    lastVerified: "2026-10-04",
  },
  {
    id: "arkworks-groth16-zksnark",
    name: "arkworks Groth16 zkSNARK",
    repository: "https://github.com/arkworks-rs/groth16",
    algorithmIds: ["zero-knowledge-proofs"],
    language: "Rust",
    interfaces: ["Rust crate", "Groth16", "R1CS-to-QAP", "Proof generation", "Pairing verification"],
    license: "MIT OR Apache-2.0",
    maturity: "Research/prototyping",
    summary: "arkworks provides a Rust implementation of the Groth16 zkSNARK; this record anchors circuit-specific reference-string generation, randomized zero-knowledge proof creation, and pairing-based verification as executable evidence.",
    implementationNotes: [
      "The pinned README identifies this repository as an efficient Groth16 zkSNARK implementation and explicitly warns that it is an academic proof-of-concept prototype that has not received careful code review and is not ready for production use.",
      "The inspected generator creates a circuit-specific common reference string from sampled parameters and explicitly labels the trapdoor inputs as toxic waste, so this record preserves Groth16's setup dependency instead of presenting the scheme as setup-free.",
      "The prover's zero-knowledge path samples fresh r and s randomness while its no-zk helper sets both to zero; the verifier checks the Groth16 pairing equation against prepared public inputs. This is executable evidence for Groth16 specifically, not a claim that all zero-knowledge protocols use the same setup, arithmetic circuit, or pairing construction.",
    ],
    sourcePaths: [
      { label: "Groth16 scope and prototype warning", url: "https://github.com/arkworks-rs/groth16/blob/8f0904a7d7a2c8945bf770bdd3c2081e0be1941a/README.md" },
      { label: "Circuit-specific reference-string generation", url: "https://github.com/arkworks-rs/groth16/blob/8f0904a7d7a2c8945bf770bdd3c2081e0be1941a/src/generator.rs" },
      { label: "Randomized zero-knowledge prover", url: "https://github.com/arkworks-rs/groth16/blob/8f0904a7d7a2c8945bf770bdd3c2081e0be1941a/src/prover.rs" },
      { label: "Pairing-based proof verifier", url: "https://github.com/arkworks-rs/groth16/blob/8f0904a7d7a2c8945bf770bdd3c2081e0be1941a/src/verifier.rs" },
      { label: "Apache-2.0 license", url: "https://github.com/arkworks-rs/groth16/blob/8f0904a7d7a2c8945bf770bdd3c2081e0be1941a/LICENSE-APACHE" },
      { label: "MIT license", url: "https://github.com/arkworks-rs/groth16/blob/8f0904a7d7a2c8945bf770bdd3c2081e0be1941a/LICENSE-MIT" },
    ],
    verifiedRef: "master",
    verifiedCommit: "8f0904a7d7a2c8945bf770bdd3c2081e0be1941a",
    lastVerified: "2026-10-04",
  },
  {
    id: "aflplusplus-coverage-guided-fuzzing",
    name: "AFL++ coverage-guided fuzzing",
    repository: "https://github.com/AFLplusplus/AFLplusplus",
    homepage: "https://aflplus.plus/",
    algorithmIds: ["coverage-guided-fuzzing"],
    language: "C / C++",
    interfaces: ["afl-fuzz CLI", "Compiler instrumentation", "Seed corpus", "Custom mutators"],
    license: "AGPL-3.0-or-later repository; Apache-2.0 for harness-compiled files as documented upstream",
    maturity: "Established open-source",
    summary: "AFL++ provides an instrumentation-guided greybox fuzzer whose core loop mutates queued test cases, executes the target, measures edge-style coverage, and retains inputs that expose new instrumented behavior.",
    implementationNotes: [
      "The pinned approach document defines the core loop explicitly: load initial cases into a queue, select an input, mutate it, and add mutations back to the queue when instrumentation records a new state transition.",
      "The inspected bitmap code classifies newly acquired traces and has_new_bits() distinguishes new hit-count states from new tuples while updating the virgin coverage map; the same source saves interesting inputs into the queue.",
      "The inspected fuzz_one() function is the mutation entry point and includes deterministic, havoc/splice, custom-mutator, and queue-scheduling paths. This record documents AFL++'s executable coverage-guided loop without claiming that every AFL++ mode, power schedule, instrumentation backend, or mutation policy behaves identically or universally improves target coverage.",
      "Licensing is intentionally recorded with upstream scope: the repository is AGPL-3.0-or-later, while the README states that files compiled into a fuzzing harness remain Apache-2.0 and each file carries its own SPDX identifier.",
    ],
    sourcePaths: [
      { label: "AFL++ scope and licensing", url: "https://github.com/AFLplusplus/AFLplusplus/blob/dbaf11913c1b2702dee5b4d3dcfffd52f1defe50/README.md" },
      { label: "Coverage-guided queue/mutation approach", url: "https://github.com/AFLplusplus/AFLplusplus/blob/dbaf11913c1b2702dee5b4d3dcfffd52f1defe50/docs/afl-fuzz_approach.md" },
      { label: "Coverage novelty and interesting-input handling", url: "https://github.com/AFLplusplus/AFLplusplus/blob/dbaf11913c1b2702dee5b4d3dcfffd52f1defe50/src/afl-fuzz-bitmap.c" },
      { label: "Mutation loop entry point", url: "https://github.com/AFLplusplus/AFLplusplus/blob/dbaf11913c1b2702dee5b4d3dcfffd52f1defe50/src/afl-fuzz-one.c" },
      { label: "Repository license", url: "https://github.com/AFLplusplus/AFLplusplus/blob/dbaf11913c1b2702dee5b4d3dcfffd52f1defe50/LICENSE" },
    ],
    verifiedRef: "stable",
    verifiedCommit: "dbaf11913c1b2702dee5b4d3dcfffd52f1defe50",
    lastVerified: "2026-10-04",
  },
  {
    id: "scip-branch-and-bound",
    name: "SCIP branch-and-bound tree",
    repository: "https://github.com/scipopt/scip",
    homepage: "https://scipopt.org/",
    algorithmIds: ["branch-and-bound"],
    language: "C",
    interfaces: ["SCIP C API", "Branching rules", "Branch-and-bound tree", "MIP/MINLP solver"],
    license: "Apache-2.0",
    maturity: "Established open-source",
    summary: "SCIP exposes an exact-search tree inside its broader branch-cut-and-price solver, with explicit child branching and bound-based cutoff of subproblems whose lower bound cannot beat the current cutoff.",
    implementationNotes: [
      "The pinned README identifies SCIP as a MIP/MINLP and constraint-integer-programming framework with branch-cut-and-price support and an optional numerically exact solving mode; this record deliberately scopes evidence to the branch-and-bound tree rather than treating presolve, cutting planes, pricing, or heuristics as textbook branch-and-bound semantics.",
      "The inspected branching API implements SCIPbranchVar/SCIPbranchVarVal for partitioning a node around a branching variable and creating child subproblems, while concrete branching rules call that API to extend the search tree.",
      "In tree.c, nodes are retained only when their lower bound is better than the cutoff bound; nodes whose lower bound is not better are cut off. primal.c updates the primal upper bound when a new best feasible solution is found and propagates the corresponding cutoff to the LP/tree machinery.",
      "SCIP's cutoff bound is not always a byte-for-byte copy of the raw incumbent objective: objective-integrality handling, objective limits, numerical tolerances, and exact mode can adjust the comparison. This record therefore supports the archive's valid-bound pruning mechanism without claiming that every SCIP pruning decision is caused only by the incumbent or that every solver uses identical tolerance logic.",
    ],
    sourcePaths: [
      { label: "SCIP solver scope", url: "https://github.com/scipopt/scip/blob/ab66fc1bbadc22fa7b03c72e3dd0d30c404e0a53/README.md" },
      { label: "Branching API and child creation", url: "https://github.com/scipopt/scip/blob/ab66fc1bbadc22fa7b03c72e3dd0d30c404e0a53/src/scip/scip_branch.c" },
      { label: "Branch-and-bound tree and cutoff pruning", url: "https://github.com/scipopt/scip/blob/ab66fc1bbadc22fa7b03c72e3dd0d30c404e0a53/src/scip/tree.c" },
      { label: "Primal bound and cutoff propagation", url: "https://github.com/scipopt/scip/blob/ab66fc1bbadc22fa7b03c72e3dd0d30c404e0a53/src/scip/primal.c" },
      { label: "Repository license", url: "https://github.com/scipopt/scip/blob/ab66fc1bbadc22fa7b03c72e3dd0d30c404e0a53/LICENSE" },
    ],
    verifiedRef: "master",
    verifiedCommit: "ab66fc1bbadc22fa7b03c72e3dd0d30c404e0a53",
    lastVerified: "2026-10-04",
  },
  {
    id: "mamba-selective-ssm",
    name: "Mamba selective state-space model",
    repository: "https://github.com/state-spaces/mamba",
    algorithmIds: ["state-space-models"],
    language: "Python / CUDA / C++",
    interfaces: ["Python API", "mamba_ssm.Mamba", "Selective scan", "Autoregressive state update"],
    license: "Apache-2.0",
    maturity: "Established open-source",
    summary: "The official Mamba repository provides the Mamba-1 selective state-space block, where input-derived state-space parameters drive a selective scan and recurrent decoding update.",
    implementationNotes: [
      "The pinned README identifies Mamba as a selective state-space architecture and points to the selective SSM layer as the focus of the original Mamba paper; the same repository now also contains Mamba-2 and Mamba-3, so this record is deliberately scoped to the Mamba-1 block and its selective scan rather than treating later generations as identical.",
      "In mamba_simple.py, the convolved input is projected and split into dt, B, and C; those input-dependent B and C values plus the input-derived time step are passed into selective_scan_fn, while the token-at-a-time step path derives the same quantities before updating the cached SSM state.",
      "selective_scan_ref exposes the recurrence directly: sequence-position-dependent B contributes to the recurrent state update and variable C reads from that state at each position. This executable reference path makes the selectivity mechanism inspectable without asserting that every optimized kernel, SSM architecture, or hardware backend shares Mamba's exact parameterization.",
      "The current README makes the CUDA selective-scan extension opt-in, and the Mamba-1 selective_scan_fn checks for that extension before using the accelerated path. This snapshot therefore does not imply that the default core package alone executes the CUDA Mamba-1 path or that its runtime requirements are universal to selective SSMs.",
    ],
    sourcePaths: [
      { label: "Mamba scope, selective-SSM interface, and installation modes", url: "https://github.com/state-spaces/mamba/blob/e9594ce1c732d97440f0332fdc43170a2294dbfa/README.md" },
      { label: "Mamba-1 block and input-dependent state parameters", url: "https://github.com/state-spaces/mamba/blob/e9594ce1c732d97440f0332fdc43170a2294dbfa/mamba_ssm/modules/mamba_simple.py" },
      { label: "Selective scan implementation and reference recurrence", url: "https://github.com/state-spaces/mamba/blob/e9594ce1c732d97440f0332fdc43170a2294dbfa/mamba_ssm/ops/selective_scan_interface.py" },
      { label: "Repository license", url: "https://github.com/state-spaces/mamba/blob/e9594ce1c732d97440f0332fdc43170a2294dbfa/LICENSE" },
    ],
    verifiedRef: "main",
    verifiedCommit: "e9594ce1c732d97440f0332fdc43170a2294dbfa",
    lastVerified: "2026-10-04",
  },
  {
    id: "pyg-graphsage",
    name: "PyTorch Geometric GraphSAGE",
    repository: "https://github.com/pyg-team/pytorch_geometric",
    homepage: "https://pytorch-geometric.readthedocs.io/",
    algorithmIds: ["graph-neural-networks"],
    language: "Python",
    interfaces: ["Python API", "torch_geometric.nn.SAGEConv", "Dense/Sparse adjacency", "MessagePassing"],
    license: "MIT",
    maturity: "Production-proven",
    summary: "PyTorch Geometric provides a production-grade SAGEConv layer implementing GraphSAGE-style neighborhood aggregation with configurable aggregators, projection, root-feature contribution, normalization, and sparse message aggregation.",
    implementationNotes: [
      "The pinned SAGEConv source defaults to mean aggregation and constructs the neighborhood contribution through PyG's MessagePassing propagation API before applying a learned linear map.",
      "When root_weight is enabled, the transformed root-node representation is added separately; optional project applies a learned nonlinear projection before aggregation and optional normalize applies L2 normalization to the output.",
      "The same implementation exposes message_and_aggregate for sparse adjacency, while the pinned tests cover mean/sum aggregation, bipartite message passing, projection, lazy inputs, LSTM/MLP/multi-aggregation variants, sparse adjacency equivalence, JIT, and torch.compile. These are implementation capabilities, not claims that every GraphSAGE formulation or GNN uses the same aggregator or systems path.",
      "This executable snapshot is scoped to PyG SAGEConv at the immutable master commit; Hamilton–Ying–Leskovec 2017 remains the primary method source and the independent JMLR benchmark remains separate empirical evidence.",
    ],
    sourcePaths: [
      { label: "SAGEConv implementation", url: "https://github.com/pyg-team/pytorch_geometric/blob/79d33965a40b7fa83616a9f598a0f8619f25d939/torch_geometric/nn/conv/sage_conv.py" },
      { label: "SAGEConv tests", url: "https://github.com/pyg-team/pytorch_geometric/blob/79d33965a40b7fa83616a9f598a0f8619f25d939/test/nn/conv/test_sage_conv.py" },
      { label: "Repository license", url: "https://github.com/pyg-team/pytorch_geometric/blob/79d33965a40b7fa83616a9f598a0f8619f25d939/LICENSE" },
    ],
    verifiedRef: "master",
    verifiedCommit: "79d33965a40b7fa83616a9f598a0f8619f25d939",
    lastVerified: "2026-10-05",
  },
];