import type { ImplementationRecord } from "./implementations.ts";

/** Generative-model implementation records kept modular from the historical registry. */
export const generativeImplementationAdditions: ImplementationRecord[] = [
  {
    id: "diffusers-ddpm",
    name: "Hugging Face Diffusers DDPM",
    repository: "https://github.com/huggingface/diffusers",
    homepage: "https://huggingface.co/docs/diffusers/",
    algorithmIds: ["diffusion-models"],
    language: "Python",
    interfaces: ["Python API", "DDPMScheduler", "DDPMPipeline", "UNet2DModel"],
    license: "Apache-2.0",
    maturity: "Production-proven",
    summary: "Hugging Face Diffusers provides an executable DDPM scheduler and unconditional image-generation pipeline implementing forward noising and iterative reverse denoising with a learned UNet.",
    implementationNotes: [
      "The pinned DDPMScheduler explicitly implements add_noise for the forward diffusion process and step for reverse-time propagation from learned model outputs, including epsilon-, sample-, and velocity-style prediction parameterizations supported by the scheduler.",
      "The pinned DDPMPipeline initializes from Gaussian noise, iterates over scheduler timesteps, predicts model output with UNet2DModel, and repeatedly calls scheduler.step to produce the previous sample until a generated image is obtained.",
      "The canonical scheduler tests exercise schedules, variance modes, deterministic full reverse loops, prediction parameterizations, and scheduler configuration behavior. The pipeline tests exercise deterministic inference output, alternate sample prediction, memory-oriented mixins, and an accelerator-gated CIFAR-10 integration path.",
      "This archive record is deliberately scoped to the DDPM scheduler/pipeline surface. Diffusers also implements many non-DDPM schedulers, conditioning systems, model architectures, and accelerated samplers that are not evidence for the canonical DDPM mechanism represented here.",
      "Ho, Jain, and Abbeel 2020 remains the primary method source. This executable snapshot corroborates implementation mechanics and tests; it does not convert library test results into claims about universal sample quality, training stability, or sampling efficiency.",
    ],
    sourcePaths: [
      { label: "DDPM scheduler", url: "https://github.com/huggingface/diffusers/blob/899c9f3fd0e64f3206781c00c71c28249eff9ca5/src/diffusers/schedulers/scheduling_ddpm.py" },
      { label: "DDPM pipeline", url: "https://github.com/huggingface/diffusers/blob/899c9f3fd0e64f3206781c00c71c28249eff9ca5/src/diffusers/pipelines/ddpm/pipeline_ddpm.py" },
      { label: "DDPM scheduler tests", url: "https://github.com/huggingface/diffusers/blob/899c9f3fd0e64f3206781c00c71c28249eff9ca5/tests/schedulers/test_scheduler_ddpm.py" },
      { label: "DDPM pipeline tests", url: "https://github.com/huggingface/diffusers/blob/899c9f3fd0e64f3206781c00c71c28249eff9ca5/tests/pipelines/ddpm/test_ddpm.py" },
      { label: "Repository license", url: "https://github.com/huggingface/diffusers/blob/899c9f3fd0e64f3206781c00c71c28249eff9ca5/LICENSE" },
    ],
    verifiedRef: "main",
    verifiedCommit: "899c9f3fd0e64f3206781c00c71c28249eff9ca5",
    lastVerified: "2026-10-06",
  },
  {
    id: "meta-flow-matching",
    name: "Meta Flow Matching",
    repository: "https://github.com/facebookresearch/flow_matching",
    homepage: "https://github.com/facebookresearch/flow_matching",
    algorithmIds: ["flow-matching"],
    language: "Python",
    interfaces: ["Python API", "ProbPath", "AffineProbPath", "PathSample", "ODESolver"],
    license: "CC BY-NC 4.0",
    maturity: "Research/prototyping",
    summary: "Meta's flow_matching library provides executable continuous and discrete Flow Matching components, including conditional probability paths, velocity targets, and ODE-based sampling from learned vector fields.",
    implementationNotes: [
      "The pinned ProbPath abstraction represents a probability path from a source distribution to a target distribution and exposes conditional path sampling for model training; PathSample carries x_t together with the conditional velocity target dx_t.",
      "AffineProbPath constructs affine conditional probability paths and its training example explicitly regresses a model against path_sample.dx_t, matching the archive's vector-field-regression Flow Matching Claim.",
      "ODESolver consumes a learned velocity model u_t(x) and integrates the resulting ODE over a requested time grid with numerical methods such as Euler, midpoint, Heun, or adaptive solvers.",
      "Pinned path tests exercise affine/conditional-OT path sampling, sample-shape invariants, and objective conversions; pinned ODE-solver tests exercise sampling, multiple integration methods, intermediate outputs, and gradient-enabled behavior.",
      "The repository is licensed CC BY-NC 4.0 and describes itself as a PyTorch research library accompanying a later Flow Matching guide/codebase. This archive therefore marks it Research/prototyping and does not treat it as a permissively licensed production dependency or as the primary theoretical source.",
    ],
    sourcePaths: [
      { label: "Probability-path abstraction", url: "https://github.com/facebookresearch/flow_matching/blob/11568d37f8d5a080e12aa7b5305d9c35ae07d136/flow_matching/path/path.py" },
      { label: "Affine probability path", url: "https://github.com/facebookresearch/flow_matching/blob/11568d37f8d5a080e12aa7b5305d9c35ae07d136/flow_matching/path/affine.py" },
      { label: "Path sample and velocity target", url: "https://github.com/facebookresearch/flow_matching/blob/11568d37f8d5a080e12aa7b5305d9c35ae07d136/flow_matching/path/path_sample.py" },
      { label: "ODE solver", url: "https://github.com/facebookresearch/flow_matching/blob/11568d37f8d5a080e12aa7b5305d9c35ae07d136/flow_matching/solver/ode_solver.py" },
      { label: "Probability-path tests", url: "https://github.com/facebookresearch/flow_matching/blob/11568d37f8d5a080e12aa7b5305d9c35ae07d136/tests/path/test_path.py" },
      { label: "ODE-solver tests", url: "https://github.com/facebookresearch/flow_matching/blob/11568d37f8d5a080e12aa7b5305d9c35ae07d136/tests/solver/test_ode_solver.py" },
      { label: "Repository README", url: "https://github.com/facebookresearch/flow_matching/blob/11568d37f8d5a080e12aa7b5305d9c35ae07d136/README.md" },
      { label: "Repository license", url: "https://github.com/facebookresearch/flow_matching/blob/11568d37f8d5a080e12aa7b5305d9c35ae07d136/LICENSE" },
    ],
    verifiedRef: "main",
    verifiedCommit: "11568d37f8d5a080e12aa7b5305d9c35ae07d136",
    lastVerified: "2026-10-06",
  },
];
