import type { ImplementationRecord } from "./implementations.ts";

/** Attention-system implementation records kept modular from the historical registry. */
export const attentionImplementationAdditions: ImplementationRecord[] = [
  {
    id: "dao-flash-attention-2",
    name: "FlashAttention-2",
    repository: "https://github.com/Dao-AILab/flash-attention",
    homepage: "https://github.com/Dao-AILab/flash-attention",
    algorithmIds: ["transformer-attention"],
    language: "Python / CUDA / ROCm",
    interfaces: ["Python API", "flash_attn_func", "Packed QKV/KV", "Variable-length attention", "KV-cache inference"],
    license: "BSD-3-Clause",
    maturity: "Established open-source",
    summary: "The official FlashAttention package exposes FlashAttention-2 exact-attention kernels through dense, packed, variable-length, and KV-cache Python APIs backed by CUDA or supported ROCm implementations.",
    implementationNotes: [
      "The pinned package identifies itself as version 2.8.4 and exports flash_attn_func together with packed-QKV/KV, variable-length, and KV-cache interfaces from the FlashAttention-2 implementation surface.",
      "The public interface dispatches exact attention to GPU kernels while preserving options such as causal masking, local windows, softmax scaling, soft-capping, dropout, and ALiBi slopes where supported; this record is scoped to the FA2 package surface rather than the separate FlashAttention-3 or FlashAttention-4 paths in the repository.",
      "The pinned canonical test suite constructs a PyTorch reference-attention implementation and exercises the exported dense, packed, variable-length, and KV-cache APIs across shapes, masks, padding, causal/local behavior, and gradients on supported GPU configurations.",
      "Hardware and toolchain support is implementation-specific: the pinned README documents PyTorch 2.2+, CUDA or ROCm toolchains, CUDA 12+ for FA2 on supported Ampere/Ada/Hopper GPUs, and ROCm 6+ with backend-specific AMD GPU and feature support. Those constraints are preserved rather than generalized into a universal attention guarantee.",
      "Dao et al. 2022 remains the primary IO-aware exact-attention method source and Dao 2024 the FlashAttention-2 work-partitioning extension; this executable snapshot does not treat benchmark speedups from either paper as guaranteed on arbitrary hardware or workloads.",
    ],
    sourcePaths: [
      { label: "FA2 package exports", url: "https://github.com/Dao-AILab/flash-attention/blob/3451a2a67a24eeed8af54d3c5b8d219577113797/flash_attn/__init__.py" },
      { label: "FA2 public interface", url: "https://github.com/Dao-AILab/flash-attention/blob/3451a2a67a24eeed8af54d3c5b8d219577113797/flash_attn/flash_attn_interface.py" },
      { label: "FA2 canonical tests", url: "https://github.com/Dao-AILab/flash-attention/blob/3451a2a67a24eeed8af54d3c5b8d219577113797/tests/test_flash_attn.py" },
      { label: "Repository README", url: "https://github.com/Dao-AILab/flash-attention/blob/3451a2a67a24eeed8af54d3c5b8d219577113797/README.md" },
      { label: "Repository license", url: "https://github.com/Dao-AILab/flash-attention/blob/3451a2a67a24eeed8af54d3c5b8d219577113797/LICENSE" },
    ],
    verifiedRef: "main",
    verifiedCommit: "3451a2a67a24eeed8af54d3c5b8d219577113797",
    lastVerified: "2026-10-05",
  },
  {
    id: "hf-switch-transformers",
    name: "Hugging Face SwitchTransformers",
    repository: "https://github.com/huggingface/transformers",
    homepage: "https://huggingface.co/docs/transformers/",
    algorithmIds: ["mixture-of-experts", "transformer-attention"],
    language: "Python / PyTorch",
    interfaces: ["Python API", "SwitchTransformersTop1Router", "SwitchTransformersSparseMLP", "SwitchTransformersForConditionalGeneration"],
    license: "Apache-2.0",
    maturity: "Established open-source",
    summary: "Hugging Face Transformers provides a Switch Transformer implementation that combines T5-style attention blocks with top-1 sparse expert routing in selected feed-forward layers.",
    implementationNotes: [
      "The pinned canonical modular source implements SwitchTransformersTop1Router by projecting token hidden states to expert logits, applying a softmax, selecting the argmax expert, enforcing per-expert capacity, and returning routing weights together with raw router logits.",
      "SwitchTransformersSparseMLP dispatches tokens through the selected experts, while SwitchTransformersLayerFF chooses between dense and sparse feed-forward modules. SwitchTransformersBlock retains T5-style self-attention/cross-attention and inserts the selected feed-forward path, directly matching the archive's MoE-plus-Transformer combination.",
      "The configuration exposes expert count, expert capacity, sparse encoder/decoder layer counts, router precision, jitter, auxiliary/z-loss coefficients, and attention settings. The pinned configuration also documents an edge case where num_sparse_*_layers=0 with a one-layer model may still create a sparse layer because of sparse-step calculation.",
      "The canonical model tests exercise sparse configurations, router logits and auxiliary/z-loss computation, generation/cache behavior, precision paths, pretrained loading, and common model invariants. These tests corroborate implementation behavior but do not establish the paper's scaling-efficiency or quality claims for arbitrary hardware or workloads.",
      "The generated modeling_switch_transformers.py file is deliberately excluded from source provenance because it is generated from modular_switch_transformers.py; this record anchors the canonical modular source instead.",
    ],
    sourcePaths: [
      { label: "Canonical SwitchTransformers modular source", url: "https://github.com/huggingface/transformers/blob/8073e6dcaea9aa4b42acf2d92ec72148786bbaeb/src/transformers/models/switch_transformers/modular_switch_transformers.py" },
      { label: "SwitchTransformers configuration", url: "https://github.com/huggingface/transformers/blob/8073e6dcaea9aa4b42acf2d92ec72148786bbaeb/src/transformers/models/switch_transformers/configuration_switch_transformers.py" },
      { label: "SwitchTransformers model tests", url: "https://github.com/huggingface/transformers/blob/8073e6dcaea9aa4b42acf2d92ec72148786bbaeb/tests/models/switch_transformers/test_modeling_switch_transformers.py" },
      { label: "Repository license", url: "https://github.com/huggingface/transformers/blob/8073e6dcaea9aa4b42acf2d92ec72148786bbaeb/LICENSE" },
    ],
    verifiedRef: "main",
    verifiedCommit: "8073e6dcaea9aa4b42acf2d92ec72148786bbaeb",
    lastVerified: "2026-10-06",
  },
];
