import type { ReferenceEntity } from "./references-core.ts";

/** Primary-source additions for foundational methods promoted into the
 * evidence graph without rewriting the historical core catalog. */
export const foundationReferenceAdditions: ReferenceEntity[] = [
  {
    id: "grover-1996-database-search",
    title: "A Fast Quantum Mechanical Algorithm for Database Search",
    authors: ["Lov K. Grover"],
    year: 1996,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "STOC 1996",
    url: "https://doi.org/10.1145/237814.237866",
    doi: "10.1145/237814.237866",
    algorithmIds: ["grover-search"],
    combinationIds: [],
    chapterSlugs: ["21-quantum-search-fourier-phase-estimation"],
    citations: [],
    notices: [],
    summary: "Introduces the quantum search procedure that alternates oracle marking with an inversion/reflection step to amplify the marked component in an unstructured search space.",
    significance: "Primary historical source for Grover search and its quadratic oracle-query improvement over classical unstructured search in the standard black-box model.",
    tags: ["grover", "quantum-search", "amplitude-amplification", "oracle"],
  },
  {
    id: "watkins-dayan-1992-q-learning",
    title: "Q-learning",
    authors: ["Christopher J. C. H. Watkins", "Peter Dayan"],
    year: 1992,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "Machine Learning 8",
    url: "https://doi.org/10.1007/BF00992698",
    doi: "10.1007/BF00992698",
    algorithmIds: ["q-learning"],
    combinationIds: [],
    chapterSlugs: ["05-probabilistic-control-reinforcement-learning"],
    citations: [],
    notices: [],
    summary: "Presents Q-learning as an incremental reinforcement-learning method for learning optimal action values directly from experience without requiring the behavior policy to be the target greedy policy.",
    significance: "Primary source for the off-policy temporal-difference control rule that became one of the central model-free reinforcement-learning foundations.",
    tags: ["q-learning", "reinforcement-learning", "temporal-difference", "off-policy"],
  },
  {
    id: "kalman-1960-linear-filtering",
    title: "A New Approach to Linear Filtering and Prediction Problems",
    authors: ["R. E. Kalman"],
    year: 1960,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "Journal of Basic Engineering 82(1)",
    url: "https://doi.org/10.1115/1.3662552",
    doi: "10.1115/1.3662552",
    algorithmIds: ["kalman-filter"],
    combinationIds: [],
    chapterSlugs: ["05-probabilistic-control-reinforcement-learning"],
    citations: [],
    notices: [],
    summary: "Develops recursive linear filtering and prediction using a state-space representation and covariance propagation, yielding the estimator now known as the Kalman filter.",
    significance: "Primary source for a foundational recursive state-estimation method that connects probabilistic inference, signal processing, robotics, and feedback control.",
    tags: ["kalman-filter", "state-estimation", "linear-systems", "gaussian-filtering"],
  },
  {
    id: "land-doig-1960-branch-bound",
    title: "An Automatic Method of Solving Discrete Programming Problems",
    authors: ["A. H. Land", "A. G. Doig"],
    year: 1960,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "Econometrica 28(3)",
    url: "https://doi.org/10.2307/1910129",
    doi: "10.2307/1910129",
    algorithmIds: ["branch-and-bound"],
    combinationIds: [],
    chapterSlugs: ["03-optimization-randomization-constraints"],
    citations: [],
    notices: [],
    summary: "Presents a systematic discrete-programming method that partitions the feasible search space and uses bounds to avoid exploring subproblems that cannot improve the best known solution.",
    significance: "Foundational historical source for the branch-and-bound family used throughout exact combinatorial and mixed-integer optimization.",
    tags: ["branch-and-bound", "discrete-programming", "exact-optimization", "bounds"],
  },
  {
    id: "jones-1998-efficient-global-optimization",
    title: "Efficient Global Optimization of Expensive Black-Box Functions",
    authors: ["Donald R. Jones", "Matthias Schonlau", "William J. Welch"],
    year: 1998,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "Journal of Global Optimization 13",
    url: "https://doi.org/10.1023/A:1008306431147",
    doi: "10.1023/A:1008306431147",
    algorithmIds: ["bayesian-optimization"],
    combinationIds: [],
    chapterSlugs: ["03-optimization-randomization-constraints", "14-uncertainty-causal-active-continual-meta-learning"],
    citations: [],
    notices: [],
    summary: "Develops Efficient Global Optimization for expensive black-box objectives using a probabilistic surrogate and expected-improvement criterion to choose sequential evaluations.",
    significance: "Canonical primary source for the surrogate-plus-acquisition-function pattern that became a central Bayesian-optimization foundation.",
    tags: ["bayesian-optimization", "efficient-global-optimization", "expected-improvement", "surrogate"],
  },
  {
    id: "khalil-2016-learning-to-branch",
    title: "Learning to Branch in Mixed Integer Programming",
    authors: ["Elias B. Khalil", "Pierre Le Bodic", "Le Song", "George Nemhauser", "Bistra Dilkina"],
    year: 2016,
    kind: "Paper",
    evidenceRole: "Primary extension",
    venue: "AAAI 2016",
    url: "https://doi.org/10.1609/aaai.v30i1.10080",
    doi: "10.1609/aaai.v30i1.10080",
    algorithmIds: ["learned-heuristics", "branch-and-bound"],
    combinationIds: [],
    chapterSlugs: ["03-optimization-randomization-constraints", "09-combination-research-map"],
    citations: [],
    notices: [],
    summary: "Introduces a machine-learning framework for branch-and-bound variable selection in mixed-integer programming by learning a ranking surrogate that imitates expensive strong-branching decisions.",
    significance: "Primary source for a concrete learned-heuristic integration inside exact branch-and-bound, grounding the archive's learned-search combination without treating the learned policy itself as the correctness boundary.",
    tags: ["branch-and-bound", "learned-heuristics", "mixed-integer-programming", "learning-to-rank", "branching"],
  },
];
