import type { ReferenceEntity } from "./references-core.ts";

/** Foundational primary sources for algorithms that previously lacked curated Claim evidence. */
export const foundationalClaimReferenceAdditions: ReferenceEntity[] = [
  {
    id: "bellman-1952-dynamic-programming",
    title: "On the Theory of Dynamic Programming",
    authors: ["Richard Bellman"],
    year: 1952,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "Proceedings of the National Academy of Sciences 38(8)",
    url: "https://doi.org/10.1073/pnas.38.8.716",
    doi: "10.1073/pnas.38.8.716",
    algorithmIds: ["dynamic-programming"],
    combinationIds: [],
    chapterSlugs: ["01-core-problem-solving-paradigms", "05-probabilistic-control-reinforcement-learning"],
    citations: [],
    notices: [],
    summary: "Bellman's early formal treatment of dynamic programming develops sequential optimization by decomposing multistage decisions into recursively related subproblems.",
    significance: "Primary historical source for dynamic programming and the state/recurrence decomposition represented by the archive's Dynamic Programming entity.",
    tags: ["dynamic-programming", "bellman", "optimal-substructure", "recurrence", "sequential-decision"],
  },
  {
    id: "gelman-2013-bayesian-data-analysis",
    title: "Bayesian Data Analysis",
    authors: ["Andrew Gelman", "John B. Carlin", "Hal S. Stern", "David B. Dunson", "Aki Vehtari", "Donald B. Rubin"],
    year: 2013,
    kind: "Book",
    evidenceRole: "Survey / synthesis",
    venue: "Chapman & Hall/CRC, 3rd edition",
    url: "https://sites.stat.columbia.edu/gelman/book/",
    algorithmIds: ["bayesian-inference"],
    combinationIds: [],
    chapterSlugs: ["05-probabilistic-control-reinforcement-learning", "14-uncertainty-causal-active-continual-meta-learning"],
    citations: [],
    notices: [],
    summary: "A comprehensive modern treatment of Bayesian data analysis organized around prior distributions, likelihoods, posterior inference, model checking, computation, and decision-making.",
    significance: "Authoritative synthesis for the archive's canonical prior-likelihood-posterior Bayesian updating Claim while satisfying the repository's modern-reference date policy.",
    tags: ["bayesian-inference", "posterior", "prior", "likelihood", "probability", "bayesian-data-analysis"],
  },
  {
    id: "mikolov-2013-word-representations",
    title: "Efficient Estimation of Word Representations in Vector Space",
    authors: ["Tomas Mikolov", "Kai Chen", "Greg Corrado", "Jeffrey Dean"],
    year: 2013,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "ICLR 2013 Workshop / arXiv:1301.3781",
    url: "https://arxiv.org/abs/1301.3781",
    algorithmIds: ["embedding-models"],
    combinationIds: [],
    chapterSlugs: ["06-representation-similarity-compression-parsing"],
    citations: [],
    notices: [],
    summary: "Introduces efficient neural architectures for learning continuous word vectors from very large corpora and evaluates the resulting geometry on syntactic and semantic word-similarity structure.",
    significance: "Primary learned-embedding source for the archive's Embedding Models entity, directly supporting continuous vector representations whose geometry encodes useful similarity structure.",
    tags: ["embeddings", "word2vec", "continuous-representation", "semantic-similarity", "representation-learning"],
  },
];
