import type { ReferenceEntity } from "./references-core.ts";

/** Primary-source additions for foundational methods promoted into the
 * evidence graph without rewriting the historical core catalog. */
export const foundationReferenceAdditions: ReferenceEntity[] = [
  {
    id: "grover-1996-database-search",
    title: "A Fast Quantum Mechanical Algorithm for Database Search",
    authors: ["Lov K. Grover"],
    year: 1996,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "STOC 1996",
    url: "https://doi.org/10.1145/237814.237866",
    doi: "10.1145/237814.237866",
    algorithmIds: ["grover-search"],
    combinationIds: [],
    chapterSlugs: ["21-quantum-search-fourier-phase-estimation"],
    citations: [],
    notices: [],
    summary: "Introduces the quantum search procedure that alternates oracle marking with an inversion/reflection step to amplify the marked component in an unstructured search space.",
    significance: "Primary historical source for Grover search and its quadratic oracle-query improvement over classical unstructured search in the standard black-box model.",
    tags: ["grover", "quantum-search", "amplitude-amplification", "oracle"],
  },
  {
    id: "watkins-dayan-1992-q-learning",
    title: "Q-learning",
    authors: ["Christopher J. C. H. Watkins", "Peter Dayan"],
    year: 1992,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "Machine Learning 8",
    url: "https://doi.org/10.1007/BF00992698",
    doi: "10.1007/BF00992698",
    algorithmIds: ["q-learning"],
    combinationIds: [],
    chapterSlugs: ["05-probabilistic-control-reinforcement-learning"],
    citations: [],
    notices: [],
    summary: "Presents Q-learning as an incremental reinforcement-learning method for learning optimal action values directly from experience without requiring the behavior policy to be the target greedy policy.",
    significance: "Primary source for the off-policy temporal-difference control rule that became one of the central model-free reinforcement-learning foundations.",
    tags: ["q-learning", "reinforcement-learning", "temporal-difference", "off-policy"],
  },
  {
    id: "kalman-1960-linear-filtering",
    title: "A New Approach to Linear Filtering and Prediction Problems",
    authors: ["R. E. Kalman"],
    year: 1960,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "Journal of Basic Engineering 82(1)",
    url: "https://doi.org/10.1115/1.3662552",
    doi: "10.1115/1.3662552",
    algorithmIds: ["kalman-filter"],
    combinationIds: [],
    chapterSlugs: ["05-probabilistic-control-reinforcement-learning"],
    citations: [],
    notices: [],
    summary: "Develops recursive linear filtering and prediction using a state-space representation and covariance propagation, yielding the estimator now known as the Kalman filter.",
    significance: "Primary source for a foundational recursive state-estimation method that connects probabilistic inference, signal processing, robotics, and feedback control.",
    tags: ["kalman-filter", "state-estimation", "linear-systems", "gaussian-filtering"],
  },
  {
    id: "land-doig-1960-branch-bound",
    title: "An Automatic Method of Solving Discrete Programming Problems",
    authors: ["A. H. Land", "A. G. Doig"],
    year: 1960,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "Econometrica 28(3)",
    url: "https://doi.org/10.2307/1910129",
    doi: "10.2307/1910129",
    algorithmIds: ["branch-and-bound"],
    combinationIds: [],
    chapterSlugs: ["03-optimization-randomization-constraints"],
    citations: [],
    notices: [],
    summary: "Presents a systematic discrete-programming method that partitions the feasible search space and uses bounds to avoid exploring subproblems that cannot improve the best known solution.",
    significance: "Foundational historical source for the branch-and-bound family used throughout exact combinatorial and mixed-integer optimization.",
    tags: ["branch-and-bound", "discrete-programming", "exact-optimization", "bounds"],
  },
  {
    id: "jones-1998-efficient-global-optimization",
    title: "Efficient Global Optimization of Expensive Black-Box Functions",
    authors: ["Donald R. Jones", "Matthias Schonlau", "William J. Welch"],
    year: 1998,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "Journal of Global Optimization 13",
    url: "https://doi.org/10.1023/A:1008306431147",
    doi: "10.1023/A:1008306431147",
    algorithmIds: ["bayesian-optimization"],
    combinationIds: [],
    chapterSlugs: ["03-optimization-randomization-constraints", "14-uncertainty-causal-active-continual-meta-learning"],
    citations: [],
    notices: [],
    summary: "Develops Efficient Global Optimization for expensive black-box objectives using a probabilistic surrogate and expected-improvement criterion to choose sequential evaluations.",
    significance: "Canonical primary source for the surrogate-plus-acquisition-function pattern that became a central Bayesian-optimization foundation.",
    tags: ["bayesian-optimization", "efficient-global-optimization", "expected-improvement", "surrogate"],
  },
  {
    id: "khalil-2016-learning-to-branch",
    title: "Learning to Branch in Mixed Integer Programming",
    authors: ["Elias B. Khalil", "Pierre Le Bodic", "Le Song", "George Nemhauser", "Bistra Dilkina"],
    year: 2016,
    kind: "Paper",
    evidenceRole: "Primary extension",
    venue: "AAAI 2016",
    url: "https://doi.org/10.1609/aaai.v30i1.10080",
    doi: "10.1609/aaai.v30i1.10080",
    algorithmIds: ["learned-heuristics", "branch-and-bound"],
    combinationIds: [],
    chapterSlugs: ["03-optimization-randomization-constraints", "09-combination-research-map"],
    citations: [],
    notices: [],
    summary: "Introduces a machine-learning framework for branch-and-bound variable selection in mixed-integer programming by learning a ranking surrogate that imitates expensive strong-branching decisions.",
    significance: "Primary source for a concrete learned-heuristic integration inside exact branch-and-bound, grounding the archive's learned-search combination without treating the learned policy itself as the correctness boundary.",
    tags: ["branch-and-bound", "learned-heuristics", "mixed-integer-programming", "learning-to-rank", "branching"],
  },
  {
    id: "cadar-2008-klee",
    title: "KLEE: Unassisted and Automatic Generation of High-Coverage Tests for Complex Systems Programs",
    authors: ["Cristian Cadar", "Daniel Dunbar", "Dawson Engler"],
    year: 2008,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "OSDI 2008",
    url: "https://www.usenix.org/conference/osdi-08/klee-unassisted-and-automatic-generation-high-coverage-tests-complex-systems",
    algorithmIds: ["symbolic-execution", "sat-smt-solving"],
    combinationIds: [],
    chapterSlugs: ["34-security-analysis-symbolic-execution-fuzzing"],
    citations: [],
    notices: [],
    summary: "Presents KLEE, a symbolic-execution system that accumulates path constraints and invokes a constraint solver to determine feasible branch directions and generate concrete high-coverage tests.",
    significance: "Primary systems source grounding the practical dependency between symbolic execution and solver-backed path reasoning represented in the Atlas.",
    tags: ["symbolic-execution", "constraint-solving", "smt", "software-testing", "klee"],
  },
  {
    id: "dennis-2002-topological-quantum-memory",
    title: "Topological Quantum Memory",
    authors: ["Eric Dennis", "Alexei Kitaev", "Andrew Landahl", "John Preskill"],
    year: 2002,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "Journal of Mathematical Physics 43",
    url: "https://arxiv.org/abs/quant-ph/0110143",
    doi: "10.1063/1.1499754",
    algorithmIds: ["error-correcting-codes", "surface-code-decoding"],
    combinationIds: [],
    chapterSlugs: ["24-quantum-error-correction-decoding", "25-fault-tolerance-error-mitigation-compilation"],
    citations: [],
    notices: [],
    summary: "Analyzes surface codes as topological quantum error-correcting codes, formulates recovery protocols, and studies thresholds under explicit noise and locality assumptions.",
    significance: "Primary source grounding the archive's coding-theory-to-surface-code-decoding relationship while keeping quantum recovery assumptions distinct from generic classical decoding.",
    tags: ["surface-code", "quantum-error-correction", "decoding", "topological-code", "threshold"],
  },
  {
    id: "stephens-2016-driller",
    title: "Driller: Augmenting Fuzzing Through Selective Symbolic Execution",
    authors: ["Nick Stephens", "John Grosen", "Christopher Salls", "Andrew Dutcher", "Ruoyu Wang", "Jacopo Corbetta", "Yan Shoshitaishvili", "Christopher Kruegel", "Giovanni Vigna"],
    year: 2016,
    kind: "Paper",
    evidenceRole: "Primary extension",
    venue: "NDSS 2016",
    url: "https://doi.org/10.14722/ndss.2016.23368",
    doi: "10.14722/ndss.2016.23368",
    algorithmIds: ["coverage-guided-fuzzing", "symbolic-execution"],
    combinationIds: [],
    chapterSlugs: ["34-security-analysis-symbolic-execution-fuzzing", "40-ai-quantum-cybersecurity-combination-map"],
    citations: [],
    notices: [],
    summary: "Presents Driller, a hybrid vulnerability-analysis system that uses fuzzing for inexpensive broad exploration and selective concolic execution to solve complex conditions that block further fuzzer progress.",
    significance: "Primary extension source for the archive's symbolic-execution/fuzzing combination, grounding a concrete division of labor between feedback-driven exploration and solver-backed path reasoning.",
    tags: ["fuzzing", "symbolic-execution", "concolic", "hybrid-testing", "security-testing"],
  },
  {
    id: "de-moura-bjorner-2008-z3",
    title: "Z3: An Efficient SMT Solver",
    authors: ["Leonardo de Moura", "Nikolaj Bjørner"],
    year: 2008,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "TACAS 2008",
    url: "https://doi.org/10.1007/978-3-540-78800-3_24",
    doi: "10.1007/978-3-540-78800-3_24",
    algorithmIds: ["sat-smt-solving"],
    combinationIds: [],
    chapterSlugs: ["34-security-analysis-symbolic-execution-fuzzing"],
    citations: [],
    notices: [],
    summary: "Presents Z3 as a Satisfiability Modulo Theories solver for first-order formulas over combinations of background theories including arithmetic, bit-vectors, arrays, and uninterpreted functions.",
    significance: "Primary systems source for a mature SMT-solving architecture and the archive's distinction between Boolean satisfiability and theory-aware constraint solving.",
    tags: ["smt", "sat", "z3", "theory-solving", "constraint-solving"],
  },
  {
    id: "gentry-2009-fully-homomorphic-encryption",
    title: "Fully Homomorphic Encryption Using Ideal Lattices",
    authors: ["Craig Gentry"],
    year: 2009,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "STOC 2009",
    url: "https://doi.org/10.1145/1536414.1536440",
    doi: "10.1145/1536414.1536440",
    algorithmIds: ["fhe", "lattice-problems"],
    combinationIds: [],
    chapterSlugs: ["33-mpc-homomorphic-encryption-differential-privacy"],
    citations: [],
    notices: [],
    summary: "Introduces the first fully homomorphic encryption construction, using ideal-lattice techniques together with bootstrapping so encrypted computations can be refreshed and extended to arbitrary circuit depth.",
    significance: "Primary historical source for fully homomorphic encryption and for the lattice-based bootstrapping lineage represented by the archive's Lattice Problems → FHE relationship.",
    tags: ["fhe", "homomorphic-encryption", "ideal-lattices", "bootstrapping", "privacy"],
  },
  {
    id: "goldreich-micali-wigderson-1987-mental-game",
    title: "How to Play ANY Mental Game",
    authors: ["Oded Goldreich", "Silvio Micali", "Avi Wigderson"],
    year: 1987,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "STOC 1987",
    url: "https://doi.org/10.1145/28395.28420",
    doi: "10.1145/28395.28420",
    algorithmIds: ["secure-multiparty-computation"],
    combinationIds: [],
    chapterSlugs: ["33-mpc-homomorphic-encryption-differential-privacy"],
    citations: [],
    notices: [],
    summary: "Presents a polynomial-time construction for general multiparty protocol problems that hides partial information under the paper's stated honest-majority setting, establishing a completeness result for secure distributed computation in that model.",
    significance: "Primary historical source for general secure multiparty computation and a direct source for the GMW lineage's use of zero-knowledge proofs to enforce correct protocol behavior against malicious deviation.",
    tags: ["secure-multiparty-computation", "mpc", "honest-majority", "zero-knowledge", "cryptographic-protocols"],
  },
];