import type { ReferenceEntity } from "./references-core.ts";

/** Primary-source additions for foundational methods promoted into the
 * evidence graph without rewriting the historical core catalog. */
export const foundationReferenceAdditions: ReferenceEntity[] = [
  {
    id: "grover-1996-database-search",
    title: "A Fast Quantum Mechanical Algorithm for Database Search",
    authors: ["Lov K. Grover"],
    year: 1996,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "STOC 1996",
    url: "https://doi.org/10.1145/237814.237866",
    doi: "10.1145/237814.237866",
    algorithmIds: ["grover-search"],
    combinationIds: [],
    chapterSlugs: ["21-quantum-search-fourier-phase-estimation"],
    citations: [],
    notices: [],
    summary: "Introduces the quantum search procedure that alternates oracle marking with an inversion/reflection step to amplify the marked component in an unstructured search space.",
    significance: "Primary historical source for Grover search and its quadratic oracle-query improvement over classical unstructured search in the standard black-box model.",
    tags: ["grover", "quantum-search", "amplitude-amplification", "oracle"],
  },
  {
    id: "watkins-dayan-1992-q-learning",
    title: "Q-learning",
    authors: ["Christopher J. C. H. Watkins", "Peter Dayan"],
    year: 1992,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "Machine Learning 8",
    url: "https://doi.org/10.1007/BF00992698",
    doi: "10.1007/BF00992698",
    algorithmIds: ["q-learning"],
    combinationIds: [],
    chapterSlugs: ["05-probabilistic-control-reinforcement-learning"],
    citations: [],
    notices: [],
    summary: "Presents Q-learning as an incremental reinforcement-learning method for learning optimal action values directly from experience without requiring the behavior policy to be the target greedy policy.",
    significance: "Primary source for the off-policy temporal-difference control rule that became one of the central model-free reinforcement-learning foundations.",
    tags: ["q-learning", "reinforcement-learning", "temporal-difference", "off-policy"],
  },
  {
    id: "kalman-1960-linear-filtering",
    title: "A New Approach to Linear Filtering and Prediction Problems",
    authors: ["R. E. Kalman"],
    year: 1960,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "Journal of Basic Engineering 82(1)",
    url: "https://doi.org/10.1115/1.3662552",
    doi: "10.1115/1.3662552",
    algorithmIds: ["kalman-filter"],
    combinationIds: [],
    chapterSlugs: ["05-probabilistic-control-reinforcement-learning"],
    citations: [],
    notices: [],
    summary: "Develops recursive linear filtering and prediction using a state-space representation and covariance propagation, yielding the estimator now known as the Kalman filter.",
    significance: "Primary source for a foundational recursive state-estimation method that connects probabilistic inference, signal processing, robotics, and feedback control.",
    tags: ["kalman-filter", "state-estimation", "linear-systems", "gaussian-filtering"],
  },
];
