import type { ReferenceEntity } from "./references-core.ts";

/** Primary attention-systems references kept modular from the historical catalog. */
export const attentionReferenceAdditions: ReferenceEntity[] = [
  {
    id: "dao-2022-flashattention",
    title: "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness",
    authors: ["Tri Dao", "Daniel Y. Fu", "Stefano Ermon", "Atri Rudra", "Christopher Ré"],
    year: 2022,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "NeurIPS 2022",
    url: "https://papers.nips.cc/paper_files/paper/2022/hash/67d57c32e20fd0a7a302cb81d36e40d5-Abstract-Conference.html",
    doi: "10.52202/068431-1189",
    algorithmIds: ["transformer-attention"],
    combinationIds: [],
    chapterSlugs: ["11-neural-architectures-attention-ssm-moe-gnn"],
    citations: [
      {
        targetId: "vaswani-2017-attention",
        note: "FlashAttention preserves exact scaled-dot-product attention semantics while reorganizing computation around GPU memory hierarchy and tiling rather than replacing the Transformer attention operator with an approximation.",
        verificationUrl: "https://papers.nips.cc/paper_files/paper/2022/file/67d57c32e20fd0a7a302cb81d36e40d5-Paper-Conference.pdf",
        verifiedAt: "2026-10-05",
      },
    ],
    notices: [],
    summary: "Introduces an IO-aware exact attention algorithm that tiles attention computation to reduce reads and writes between GPU high-bandwidth memory and on-chip SRAM.",
    significance: "Primary source for the systems insight that preserving exact attention semantics can still yield major runtime and memory improvements by optimizing data movement rather than only arithmetic complexity.",
    tags: ["flashattention", "attention", "transformer", "io-awareness", "tiling", "gpu-memory", "exact-attention"],
  },
  {
    id: "dao-2024-flashattention-2",
    title: "FlashAttention-2: Faster Attention with Better Parallelism and Work Partitioning",
    authors: ["Tri Dao"],
    year: 2024,
    kind: "Paper",
    evidenceRole: "Primary extension",
    venue: "ICLR 2024",
    url: "https://openreview.net/forum?id=mZn2Xyh9Ec",
    algorithmIds: ["transformer-attention"],
    combinationIds: [],
    chapterSlugs: ["11-neural-architectures-attention-ssm-moe-gnn"],
    citations: [
      {
        targetId: "dao-2022-flashattention",
        note: "FlashAttention-2 explicitly extends FlashAttention with improved work partitioning across thread blocks and warps while retaining exact attention semantics.",
        verificationUrl: "https://openreview.net/forum?id=mZn2Xyh9Ec",
        verifiedAt: "2026-10-05",
      },
    ],
    notices: [],
    summary: "Extends FlashAttention by reducing non-matmul work and improving thread-block and warp-level work partitioning to raise GPU occupancy and reduce shared-memory communication.",
    significance: "Primary extension for the FlashAttention-2 implementation family represented by the archive's executable snapshot; it refines parallel execution rather than changing the underlying exact-attention objective.",
    tags: ["flashattention-2", "attention", "transformer", "gpu", "parallelism", "work-partitioning", "exact-attention"],
  },
  {
    id: "fedus-2022-switch-transformer",
    title: "Switch Transformers: Scaling to Trillion Parameter Models with Simple and Efficient Sparsity",
    authors: ["William Fedus", "Barret Zoph", "Noam Shazeer"],
    year: 2022,
    kind: "Paper",
    evidenceRole: "Primary extension",
    venue: "JMLR 23(120)",
    url: "https://www.jmlr.org/papers/v23/21-0998.html",
    algorithmIds: ["mixture-of-experts", "transformer-attention"],
    combinationIds: [],
    chapterSlugs: ["11-neural-architectures-attention-ssm-moe-gnn"],
    citations: [
      {
        targetId: "shazeer-2017-sparsely-gated-moe",
        note: "Switch Transformer simplifies the sparse mixture-of-experts routing lineage introduced by Shazeer et al. while embedding expert routing into a Transformer language-model architecture.",
        verificationUrl: "https://jmlr.org/papers/volume23/21-0998/21-0998.pdf",
        verifiedAt: "2026-10-06",
      },
      {
        targetId: "vaswani-2017-attention",
        note: "Fedus, Zoph, and Shazeer construct Switch Transformer from Transformer/T5 models and replace dense feed-forward capacity with sparse expert routing while retaining the Transformer attention stack.",
        verificationUrl: "https://jmlr.org/papers/volume23/21-0998/21-0998.pdf",
        verifiedAt: "2026-10-06",
      },
    ],
    notices: [],
    summary: "Introduces Switch Transformer, a sparse mixture-of-experts Transformer that routes each token to a single expert to increase model capacity while controlling active computation and communication complexity.",
    significance: "Primary extension directly grounding the archive's MoE-and-Transformer combination: sparse expert routing is inserted into Transformer models to provide conditional parameter capacity rather than activating every feed-forward parameter for every token.",
    tags: ["switch-transformer", "mixture-of-experts", "moe", "transformer", "sparse-routing", "conditional-computation", "expert-routing"],
  },
];
