import type { ReferenceEntity } from "./references-core.ts";

/** Primary AI/ML references added without rewriting the historical core catalog. */
export const aiReferenceAdditions: ReferenceEntity[] = [
  {
    id: "shazeer-2017-sparsely-gated-moe",
    title: "Outrageously Large Neural Networks: The Sparsely-Gated Mixture-of-Experts Layer",
    authors: ["Noam Shazeer", "Azalia Mirhoseini", "Krzysztof Maziarz", "Andy Davis", "Quoc V. Le", "Geoffrey Hinton", "Jeff Dean"],
    year: 2017,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "ICLR 2017",
    url: "https://arxiv.org/abs/1701.06538",
    algorithmIds: ["mixture-of-experts"],
    combinationIds: [],
    chapterSlugs: ["11-neural-architectures-attention-ssm-moe-gnn"],
    citations: [],
    notices: [],
    summary: "Introduces a sparsely gated mixture-of-experts layer in which a trainable gating network selects a sparse combination from many feed-forward expert subnetworks for each example.",
    significance: "Primary source for modern sparse expert routing and conditional computation that expands model capacity without activating every parameter for every input.",
    tags: ["mixture-of-experts", "moe", "conditional-computation", "sparse-routing", "expert-routing"],
  },
  {
    id: "kipf-welling-2017-gcn",
    title: "Semi-Supervised Classification with Graph Convolutional Networks",
    authors: ["Thomas N. Kipf", "Max Welling"],
    year: 2017,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "ICLR 2017",
    url: "https://arxiv.org/abs/1609.02907",
    algorithmIds: ["graph-neural-networks"],
    combinationIds: [],
    chapterSlugs: ["11-neural-architectures-attention-ssm-moe-gnn"],
    citations: [],
    notices: [],
    summary: "Presents a scalable graph convolutional network based on a localized first-order approximation of spectral graph convolutions, propagating graph structure and node features through normalized graph-aware layers.",
    significance: "Primary source for the widely used GCN propagation pattern represented by the archive's graph-neural-network family.",
    tags: ["graph-neural-network", "gcn", "graph-convolution", "message-passing", "semi-supervised-learning"],
  },
  {
    id: "hamilton-2017-graphsage",
    title: "Inductive Representation Learning on Large Graphs",
    authors: ["William L. Hamilton", "Rex Ying", "Jure Leskovec"],
    year: 2017,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "NeurIPS 2017",
    url: "https://arxiv.org/abs/1706.02216",
    algorithmIds: ["graph-neural-networks"],
    combinationIds: [],
    chapterSlugs: ["11-neural-architectures-attention-ssm-moe-gnn"],
    citations: [],
    notices: [],
    summary: "Introduces GraphSAGE, an inductive framework that learns functions for generating node representations by sampling and aggregating features from local graph neighborhoods.",
    significance: "Primary source for sampled neighborhood aggregation and inductive graph representation learning that can generate representations for previously unseen nodes or graphs.",
    tags: ["graphsage", "graph-neural-network", "inductive-learning", "neighborhood-sampling", "message-passing"],
  },
  {
    id: "velickovic-2018-gat",
    title: "Graph Attention Networks",
    authors: ["Petar Veličković", "Guillem Cucurull", "Arantxa Casanova", "Adriana Romero", "Pietro Liò", "Yoshua Bengio"],
    year: 2018,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "ICLR 2018",
    url: "https://arxiv.org/abs/1710.10903",
    algorithmIds: ["graph-neural-networks"],
    combinationIds: [],
    chapterSlugs: ["11-neural-architectures-attention-ssm-moe-gnn"],
    citations: [],
    notices: [],
    summary: "Introduces Graph Attention Networks, where masked self-attention assigns learned coefficients to neighboring nodes before aggregating their transformed features.",
    significance: "Primary source for replacing fixed neighborhood weighting with learned attention coefficients in graph message passing, connecting graph neural networks directly to attention mechanisms.",
    tags: ["graph-attention-network", "gat", "graph-neural-network", "attention", "message-passing", "multi-head-attention"],
  },
  {
    id: "ying-2021-graphormer",
    title: "Do Transformers Really Perform Badly for Graph Representation?",
    authors: ["Chengxuan Ying", "Tianle Cai", "Shengjie Luo", "Shuxin Zheng", "Guolin Ke", "Di He", "Yanming Shen", "Tie-Yan Liu"],
    year: 2021,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "NeurIPS 2021",
    url: "https://openreview.net/forum?id=OeWooOxFwDa",
    algorithmIds: ["graph-neural-networks", "transformer-attention"],
    combinationIds: [],
    chapterSlugs: ["11-neural-architectures-attention-ssm-moe-gnn"],
    citations: [
      {
        targetId: "vaswani-2017-attention",
        note: "Ying et al. build Graphormer directly on the standard Transformer architecture and add graph-structural encodings so self-attention can incorporate node and pairwise graph structure.",
        verificationUrl: "https://openreview.net/pdf?id=OeWooOxFwDa",
        verifiedAt: "2026-10-05",
      },
    ],
    notices: [],
    summary: "Introduces Graphormer, a Transformer-based graph representation architecture that injects structural information such as node centrality and pairwise graph structure into node features and attention computation.",
    significance: "Primary source for a graph-Transformer design that keeps standard Transformer attention while making graph topology explicit through structural encodings rather than relying only on local message passing.",
    tags: ["graphormer", "graph-transformer", "graph-neural-network", "transformer", "structural-encoding", "attention"],
  },
  {
    id: "agostinelli-2019-deepcubea",
    title: "Solving the Rubik’s cube with deep reinforcement learning and search",
    authors: ["Forest Agostinelli", "Stephen McAleer", "Alexander Shmakov", "Pierre Baldi"],
    year: 2019,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "Nature Machine Intelligence 1, 356–363",
    url: "https://www.nature.com/articles/s42256-019-0070-z",
    doi: "10.1038/s42256-019-0070-z",
    algorithmIds: ["learned-heuristics", "a-star"],
    combinationIds: [],
    chapterSlugs: ["02-search-graphs-ordering-indexing", "13-ai-reasoning-alignment-agents"],
    citations: [
      {
        targetId: "hart-1968-a-star",
        note: "DeepCubeA learns a cost-to-go estimate and uses it inside a weighted A* search procedure, extending classical heuristic search with a learned heuristic rather than replacing explicit state-space search.",
        verificationUrl: "https://www.nature.com/articles/s42256-019-0070-z",
        verifiedAt: "2026-10-07",
      },
    ],
    notices: [],
    summary: "Introduces DeepCubeA, which learns a neural cost-to-go function from self-generated experience and combines that learned heuristic with weighted A* search for large combinatorial puzzles.",
    significance: "Direct primary support for the archive's Learned-Heuristics-to-A* relationship: a learned value/cost-to-go estimate guides explicit graph search, while search guarantees remain sensitive to weighting and heuristic admissibility.",
    tags: ["learned-heuristics", "a-star", "weighted-a-star", "deep-reinforcement-learning", "cost-to-go", "search"],
  },
];
