import type { ReferenceEntity } from "./references-core.ts";

/** Foundational primary sources for algorithms that previously lacked curated Claim evidence. */
export const foundationalClaimReferenceAdditions: ReferenceEntity[] = [
  {
    id: "bellman-1952-dynamic-programming",
    title: "On the Theory of Dynamic Programming",
    authors: ["Richard Bellman"],
    year: 1952,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "Proceedings of the National Academy of Sciences 38(8)",
    url: "https://doi.org/10.1073/pnas.38.8.716",
    doi: "10.1073/pnas.38.8.716",
    algorithmIds: ["dynamic-programming"],
    combinationIds: [],
    chapterSlugs: ["01-core-problem-solving-paradigms", "05-probabilistic-control-reinforcement-learning"],
    citations: [],
    notices: [],
    summary: "Bellman's early formal treatment of dynamic programming develops sequential optimization by decomposing multistage decisions into recursively related subproblems.",
    significance: "Primary historical source for dynamic programming and the state/recurrence decomposition represented by the archive's Dynamic Programming entity.",
    tags: ["dynamic-programming", "bellman", "optimal-substructure", "recurrence", "sequential-decision"],
  },
  {
    id: "bayes-1763-doctrine-chances",
    title: "An Essay towards Solving a Problem in the Doctrine of Chances",
    authors: ["Thomas Bayes"],
    year: 1763,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "Philosophical Transactions of the Royal Society of London 53",
    url: "https://doi.org/10.1098/rstl.1763.0053",
    doi: "10.1098/rstl.1763.0053",
    algorithmIds: ["bayesian-inference"],
    combinationIds: [],
    chapterSlugs: ["05-probabilistic-control-reinforcement-learning", "14-uncertainty-causal-active-continual-meta-learning"],
    citations: [],
    notices: [],
    summary: "Bayes's posthumously published essay develops inverse-probability reasoning for updating uncertainty about an unknown chance from observed outcomes.",
    significance: "Foundational primary source for the prior-evidence-posterior updating pattern represented by the archive's Bayesian Inference entity.",
    tags: ["bayes", "bayesian-inference", "posterior", "prior", "likelihood", "probability"],
  },
  {
    id: "mikolov-2013-word-representations",
    title: "Efficient Estimation of Word Representations in Vector Space",
    authors: ["Tomas Mikolov", "Kai Chen", "Greg Corrado", "Jeffrey Dean"],
    year: 2013,
    kind: "Paper",
    evidenceRole: "Primary method",
    venue: "ICLR 2013 Workshop / arXiv:1301.3781",
    url: "https://arxiv.org/abs/1301.3781",
    algorithmIds: ["embedding-models"],
    combinationIds: [],
    chapterSlugs: ["06-representation-similarity-compression-parsing"],
    citations: [],
    notices: [],
    summary: "Introduces efficient neural architectures for learning continuous word vectors from very large corpora and evaluates the resulting geometry on syntactic and semantic word-similarity structure.",
    significance: "Primary learned-embedding source for the archive's Embedding Models entity, directly supporting continuous vector representations whose geometry encodes useful similarity structure.",
    tags: ["embeddings", "word2vec", "continuous-representation", "semantic-similarity", "representation-learning"],
  },
];
